# pymongo operations

### sending records, receiving records, renaming categorical values in categorical columns

In [5]:
import os
os.getcwd()

'c:\\Users\\mriyu\\OneDrive\\Desktop\\DS2026\\MLOPs March 2026_Alexey\\06_Decision tree\\Credit_risk\\notebooks'

In [6]:
os.listdir()

['credit_risk.ipynb', 'mongodb_demo.ipynb', 'monodb_data.ipynb']

In [1]:
import pandas as pd

In [8]:
# Exploring and basic cleaning of data
df = pd.read_csv(r"../data/CreditScoring.csv")

In [9]:
df.head()

,Status,Seniority,Home,Time,Age,Marital,Records,Job,Expenses,Income,Assets,Debt,Amount,Price
0,1,9,1,60,30,2,1,3,73,129,0,0,800,846
1,1,17,1,60,58,3,1,1,48,131,0,0,1000,1658
2,2,10,2,36,46,2,2,3,90,200,3000,0,2000,2985
3,1,0,1,60,24,1,1,1,63,182,2500,0,900,1325
4,1,0,1,36,26,1,1,1,46,107,0,0,310,910

In [10]:
df.columns

Index(['Status', 'Seniority', 'Home', 'Time', 'Age', 'Marital', 'Records',
       'Job', 'Expenses', 'Income', 'Assets', 'Debt', 'Amount', 'Price'],
      dtype='object')

In [12]:
df.columns = df.columns.str.lower()

In [13]:
df.head(5)

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,1,9,1,60,30,2,1,3,73,129,0,0,800,846
1,1,17,1,60,58,3,1,1,48,131,0,0,1000,1658
2,2,10,2,36,46,2,2,3,90,200,3000,0,2000,2985
3,1,0,1,60,24,1,1,1,63,182,2500,0,900,1325
4,1,0,1,36,26,1,1,1,46,107,0,0,310,910

In [ ]:
'''
 status: whether the customer managed to pay back the loan (1) or not (2)
 seniority: job experience in years
 home: type of homeownership: renting (1), a homeowner (2), and others
 time: period planned for the loan (in months)
 age: age of the client
 marital [status]: single (1), married (2), and others
 records: whether the client has any previous records: no (1), yes (2)
 job: type of job: full-time (1), part-time (2), and others
 expenses: how much the client spends per month
 income: how much the client earns per month
 assets: total worth of all the assets of the client
 debt: amount of credit debt
 amount: requested amount of the loan
 price: price of an item the client wants to buy
'''

'\n\uf0a1 status: whether the customer managed to pay back the loan (1) or not (2)\n\uf0a1 seniority: job experience in years\n\uf0a1 home: type of homeownership: renting (1), a homeowner (2), and others\n\uf0a1 time: period planned for the loan (in months)\n\uf0a1 age: age of the client\n\uf0a1 marital [status]: single (1), married (2), and others\n\uf0a1 records: whether the client has any previous records: no (1), yes (2) (It’s not\nclear from the dataset description what kind of records we have in this column.\nFor the purposes of this project, we may assume that it’s about records in the\nbank’s database.)\n\uf0a1 job: type of job: full-time (1), part-time (2), and others\n\uf0a1 expenses: how much the client spends per month\n\uf0a1 income: how much the client earns per month\n\uf0a1 assets: total worth of all the assets of the client\n\uf0a1 debt: amount of credit debt\n\uf0a1 amount: requested amount of the loan\n\uf0a1 price: price of an item the client wants to buy\n'

In [15]:
df.columns

Index(['status', 'seniority', 'home', 'time', 'age', 'marital', 'records',
       'job', 'expenses', 'income', 'assets', 'debt', 'amount', 'price'],
      dtype='object')

In [17]:
data = df.to_dict(orient="records")
data

[{'status': 1,
  'seniority': 9,
  'home': 1,
  'time': 60,
  'age': 30,
  'marital': 2,
  'records': 1,
  'job': 3,
  'expenses': 73,
  'income': 129,
  'assets': 0,
  'debt': 0,
  'amount': 800,
  'price': 846},
 {'status': 1,
  'seniority': 17,
  'home': 1,
  'time': 60,
  'age': 58,
  'marital': 3,
  'records': 1,
  'job': 1,
  'expenses': 48,
  'income': 131,
  'assets': 0,
  'debt': 0,
  'amount': 1000,
  'price': 1658},
 {'status': 2,
  'seniority': 10,
  'home': 2,
  'time': 36,
  'age': 46,
  'marital': 2,
  'records': 2,
  'job': 3,
  'expenses': 90,
  'income': 200,
  'assets': 3000,
  'debt': 0,
  'amount': 2000,
  'price': 2985},
 {'status': 1,
  'seniority': 0,
  'home': 1,
  'time': 60,
  'age': 24,
  'marital': 1,
  'records': 1,
  'job': 1,
  'expenses': 63,
  'income': 182,
  'assets': 2500,
  'debt': 0,
  'amount': 900,
  'price': 1325},
 {'status': 1,
  'seniority': 0,
  'home': 1,
  'time': 36,
  'age': 26,
  'marital': 1,
  'records': 1,
  'job': 1,
  'expenses': 46,
  'income': 107,
  'assets': 0,
  'debt': 0,
  'amount': 310,
  'price': 910},
 {'status': 1,
  'seniority': 1,
  'home': 2,
  'time': 60,
  'age': 36,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 214,
  'assets': 3500,
  'debt': 0,
  'amount': 650,
  'price': 1645},
 {'status': 1,
  'seniority': 29,
  'home': 2,
  'time': 60,
  'age': 44,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 125,
  'assets': 10000,
  'debt': 0,
  'amount': 1600,
  'price': 1800},
 {'status': 1,
  'seniority': 9,
  'home': 5,
  'time': 12,
  'age': 27,
  'marital': 1,
  'records': 1,
  'job': 1,
  'expenses': 35,
  'income': 80,
  'assets': 0,
  'debt': 0,
  'amount': 200,
  'price': 1093},
 {'status': 1,
  'seniority': 0,
  'home': 2,
  'time': 60,
  'age': 32,
  'marital': 2,
  'records': 1,
  'job': 3,
  'expenses': 90,
  'income': 107,
  'assets': 15000,
  'debt': 0,
  'amount': 1200,
  'price': 1957},
 {'status': 2,
  'seniority': 0,
  'home': 5,
  'time': 48,
  'age': 41,
  'marital': 2,
  'records': 1,
  'job': 2,
  'expenses': 90,
  'income': 80,
  'assets': 0,
  'debt': 0,
  'amount': 1200,
  'price': 1468},
 {'status': 1,
  'seniority': 6,
  'home': 2,
  'time': 48,
  'age': 34,
  'marital': 2,
  'records': 1,
  'job': 3,
  'expenses': 60,
  'income': 125,
  'assets': 4000,
  'debt': 0,
  'amount': 1150,
  'price': 1577},
 {'status': 1,
  'seniority': 7,
  'home': 2,
  'time': 36,
  'age': 29,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 60,
  'income': 121,
  'assets': 3000,
  'debt': 0,
  'amount': 650,
  'price': 915},
 {'status': 1,
  'seniority': 8,
  'home': 2,
  'time': 60,
  'age': 30,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 199,
  'assets': 5000,
  'debt': 2500,
  'amount': 1500,
  'price': 1650},
 {'status': 1,
  'seniority': 19,
  'home': 3,
  'time': 36,
  'age': 37,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 170,
  'assets': 3500,
  'debt': 260,
  'amount': 600,
  'price': 940},
 {'status': 2,
  'seniority': 0,
  'home': 6,
  'time': 18,
  'age': 21,
  'marital': 1,
  'records': 2,
  'job': 2,
  'expenses': 35,
  'income': 50,
  'assets': 0,
  'debt': 0,
  'amount': 400,
  'price': 500},
 {'status': 1,
  'seniority': 0,
  'home': 2,
  'time': 24,
  'age': 68,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 131,
  'assets': 4162,
  'debt': 0,
  'amount': 900,
  'price': 1186},
 {'status': 1,
  'seniority': 15,
  'home': 3,
  'time': 24,
  'age': 52,
  'marital': 1,
  'records': 1,
  'job': 3,
  'expenses': 35,
  'income': 330,
  'assets': 16500,
  'debt': 0,
  'amount': 1500,
  'price': 2201},
 {'status': 1,
  'seniority': 33,
  'home': 1,
  'time': 24,
  'age': 68,
  'marital': 2,
  'records': 1,
  'job': 3,
  'expenses': 65,
  'income': 200,
  'assets': 5000,
  'debt': 2000,
  'amount': 600,
  'price': 1350},
 {'status': 2,
  'seniority': 0,
  'home': 4,
  'time': 48,
  'age': 36,
  'marital': 2,
  'records': 1,
  'job': 2,
  'expenses': 45,
  'income': 130,
  'assets': 750,
  'debt': 0,
  'amount': 1100,
  'price': 1511},
 {'status': 1,
  'seniority': 1,
  'home': 5,
  'time': 60,
  'age': 31,
  'marital': 1,
  'records': 1,
  'job': 1,
  'expenses': 35,
  'income': 137,
  'assets': 0,
  'debt': 0,
  'amount': 1250,
  'price': 1253},
 {'status': 2,
  'seniority': 2,
  'home': 1,
  'time': 60,
  'age': 25,
  'marital': 1,
  'records': 1,
  'job': 1,
  'expenses': 46,
  'income': 107,
  'assets': 0,
  'debt': 0,
  'amount': 1500,
  'price': 2189},
 {'status': 1,
  'seniority': 5,
  'home': 2,
  'time': 60,
  'age': 22,
  'marital': 1,
  'records': 1,
  'job': 1,
  'expenses': 45,
  'income': 324,
  'assets': 10000,
  'debt': 0,
  'amount': 1100,
  'price': 1159},
 {'status': 2,
  'seniority': 1,
  'home': 2,
  'time': 60,
  'age': 45,
  'marital': 2,
  'records': 1,
  'job': 2,
  'expenses': 105,
  'income': 112,
  'assets': 2000,
  'debt': 500,
  'amount': 600,
  'price': 1332},
 {'status': 1,
  'seniority': 27,
  'home': 1,
  'time': 60,
  'age': 41,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 74,
  'income': 140,
  'assets': 0,
  'debt': 0,
  'amount': 950,
  'price': 1497},
 {'status': 1,
  'seniority': 26,
  'home': 2,
  'time': 60,
  'age': 51,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 45,
  'income': 143,
  'assets': 3500,
  'debt': 0,
  'amount': 1350,
  'price': 1357},
 {'status': 1,
  'seniority': 12,
  'home': 2,
  'time': 36,
  'age': 54,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 60,
  'income': 130,
  'assets': 4000,
  'debt': 0,
  'amount': 700,
  'price': 2100},
 {'status': 1,
  'seniority': 19,
  'home': 2,
  'time': 60,
  'age': 43,
  'marital': 1,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 180,
  'assets': 4000,
  'debt': 0,
  'amount': 1000,
  'price': 1070},
 {'status': 1,
  'seniority': 15,
  'home': 2,
  'time': 36,
  'age': 43,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 251,
  'assets': 4000,
  'debt': 0,
  'amount': 1800,
  'price': 2557},
 {'status': 2,
  'seniority': 3,
  'home': 2,
  'time': 24,
  'age': 23,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 85,
  'assets': 5000,
  'debt': 0,
  'amount': 600,
  'price': 1600},
 {'status': 2,
  'seniority': 0,
  'home': 0,
  'time': 48,
  'age': 37,
  'marital': 1,
  'records': 1,
  'job': 0,
  'expenses': 35,
  'income': 99999999,
  'assets': 99999999,
  'debt': 99999999,
  'amount': 1500,
  'price': 1850},
 {'status': 1,
  'seniority': 4,
  'home': 2,
  'time': 48,
  'age': 29,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 45,
  'income': 150,
  'assets': 5000,
  'debt': 3300,
  'amount': 1100,
  'price': 1312},
 {'status': 2,
  'seniority': 0,
  'home': 2,
  'time': 36,
  'age': 23,
  'marital': 1,
  'records': 1,
  'job': 2,
  'expenses': 45,
  'income': 122,
  'assets': 2500,
  'debt': 0,
  'amount': 400,
  'price': 400},
 {'status': 1,
  'seniority': 14,
  'home': 3,
  'time': 24,
  'age': 51,
  'marital': 2,
  'records': 1,
  'job': 2,
  'expenses': 75,
  'income': 198,
  'assets': 1000,
  'debt': 0,
  'amount': 450,
  'price': 650},
 {'status': 1,
  'seniority': 10,
  'home': 2,
  'time': 36,
  'age': 39,
  'marital': 2,
  'records': 1,
  'job': 3,
  'expenses': 75,
  'income': 150,
  'assets': 3000,
  'debt': 0,
  'amount': 1000,
  'price': 1394},
 {'status': 1,
  'seniority': 12,
  'home': 5,
  'time': 36,
  'age': 35,
  'marital': 1,
  'records': 1,
  'job': 1,
  'expenses': 35,
  'income': 170,
  'assets': 0,
  'debt': 0,
  'amount': 1100,
  'price': 1542},
 {'status': 1,
  'seniority': 32,
  'home': 2,
  'time': 24,
  'age': 62,
  'marital': 2,
  'records': 1,
  'job': 3,
  'expenses': 45,
  'income': 119,
  'assets': 8500,
  'debt': 0,
  'amount': 700,
  'price': 1200},
 {'status': 1,
  'seniority': 10,
  'home': 2,
  'time': 24,
  'age': 56,
  'marital': 2,
  'records': 1,
  'job': 3,
  'expenses': 45,
  'income': 208,
  'assets': 13500,
  'debt': 0,
  'amount': 500,
  'price': 1560},
 {'status': 1,
  'seniority': 7,
  'home': 2,
  'time': 48,
  'age': 32,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 115,
  'assets': 3000,
  'debt': 0,
  'amount': 800,
  'price': 1200},
 {'status': 2,
  'seniority': 1,
  'home': 1,
  'time': 54,
  'age': 36,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 70,
  'income': 99,
  'assets': 0,
  'debt': 0,
  'amount': 950,
  'price': 950},
 {'status': 1,
  'seniority': 30,
  'home': 2,
  'time': 60,
  'age': 64,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 45,
  'income': 120,
  'assets': 14000,
  'debt': 0,
  'amount': 1125,
  'price': 1300},
 {'status': 2,
  'seniority': 5,
  'home': 1,
  'time': 48,
  'age': 31,
  'marital': 1,
  'records': 1,
  'job': 1,
  'expenses': 44,
  'income': 90,
  'assets': 0,
  'debt': 0,
  'amount': 1300,
  'price': 1700},
 {'status': 1,
  'seniority': 24,
  'home': 2,
  'time': 60,
  'age': 42,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 137,
  'assets': 4000,
  'debt': 0,
  'amount': 900,
  'price': 1167},
 {'status': 1,
  'seniority': 0,
  'home': 2,
  'time': 60,
  'age': 61,
  'marital': 3,
  'records': 1,
  'job': 4,
  'expenses': 35,
  'income': 230,
  'assets': 50000,
  'debt': 0,
  'amount': 950,
  'price': 1150},
 {'status': 2,
  'seniority': 0,
  'home': 2,
  'time': 60,
  'age': 32,
  'marital': 2,
  'records': 2,
  'job': 1,
  'expenses': 45,
  'income': 142,
  'assets': 7000,
  'debt': 3000,
  'amount': 1250,
  'price': 1566},
 {'status': 2,
  'seniority': 2,
  'home': 2,
  'time': 60,
  'age': 43,
  'marital': 2,
  'records': 1,
  'job': 2,
  'expenses': 75,
  'income': 71,
  'assets': 3000,
  'debt': 0,
  'amount': 1500,
  'price': 1552},
 {'status': 1,
  'seniority': 1,
  'home': 5,
  'time': 60,
  'age': 26,
  'marital': 1,
  'records': 1,
  'job': 2,
  'expenses': 35,
  'income': 120,
  'assets': 0,
  'debt': 0,
  'amount': 1150,
  'price': 1300},
 {'status': 1,
  'seniority': 1,
  'home': 2,
  'time': 60,
  'age': 49,
  'marital': 3,
  'records': 1,
  'job': 3,
  'expenses': 35,
  'income': 233,
  'assets': 15900,
  'debt': 4500,
  'amount': 2100,
  'price': 2104},
 {'status': 1,
  'seniority': 15,
  'home': 2,
  'time': 36,
  'age': 47,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 289,
  'assets': 3500,
  'debt': 0,
  'amount': 1500,
  'price': 2154},
 {'status': 2,
  'seniority': 2,
  'home': 1,
  'time': 36,
  'age': 27,
  'marital': 4,
  'records': 1,
  'job': 1,
  'expenses': 48,
  'income': 128,
  'assets': 0,
  'debt': 0,
  'amount': 450,
  'price': 545},
 {'status': 1,
  'seniority': 25,
  'home': 2,
  'time': 36,
  'age': 52,
  'marital': 2,
  'records': 1,
  'job': 3,
  'expenses': 60,
  'income': 150,
  'assets': 15000,
  'debt': 0,
  'amount': 750,
  'price': 1778},
 {'status': 1,
  'seniority': 8,
  'home': 2,
  'time': 60,
  'age': 28,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 60,
  'income': 145,
  'assets': 4000,
  'debt': 1000,
  'amount': 1600,
  'price': 1718},
 {'status': 1,
  'seniority': 5,
  'home': 2,
  'time': 60,
  'age': 31,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 90,
  'assets': 4000,
  'debt': 0,
  'amount': 900,
  'price': 1500},
 {'status': 1,
  'seniority': 0,
  'home': 1,
  'time': 60,
  'age': 32,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 105,
  'income': 301,
  'assets': 0,
  'debt': 0,
  'amount': 1200,
  'price': 1274},
 {'status': 1,
  'seniority': 5,
  'home': 2,
  'time': 36,
  'age': 51,
  'marital': 2,
  'records': 1,
  'job': 3,
  'expenses': 75,
  'income': 200,
  'assets': 2100,
  'debt': 1200,
  'amount': 900,
  'price': 1015},
 {'status': 1,
  'seniority': 3,
  'home': 5,
  'time': 12,
  'age': 37,
  'marital': 2,
  'records': 1,
  'job': 3,
  'expenses': 60,
  'income': 150,
  'assets': 500,
  'debt': 0,
  'amount': 500,
  'price': 1701},
 {'status': 2,
  'seniority': 1,
  'home': 1,
  'time': 48,
  'age': 29,
  'marital': 2,
  'records': 2,
  'job': 3,
  'expenses': 85,
  'income': 100,
  'assets': 0,
  'debt': 0,
  'amount': 1000,
  'price': 1345},
 {'status': 1,
  'seniority': 7,
  'home': 5,
  'time': 60,
  'age': 26,
  'marital': 1,
  'records': 1,
  'job': 1,
  'expenses': 35,
  'income': 100,
  'assets': 0,
  'debt': 0,
  'amount': 1000,
  'price': 1238},
 {'status': 1,
  'seniority': 4,
  'home': 5,
  'time': 30,
  'age': 27,
  'marital': 1,
  'records': 1,
  'job': 1,
  'expenses': 45,
  'income': 100,
  'assets': 5000,
  'debt': 0,
  'amount': 500,
  'price': 1048},
 {'status': 1,
  'seniority': 6,
  'home': 2,
  'time': 24,
  'age': 63,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 60,
  'income': 155,
  'assets': 4000,
  'debt': 0,
  'amount': 600,
  'price': 1048},
 {'status': 1,
  'seniority': 14,
  'home': 2,
  'time': 24,
  'age': 55,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 90,
  'income': 715,
  'assets': 5000,
  'debt': 0,
  'amount': 800,
  'price': 1324},
 {'status': 1,
  'seniority': 3,
  'home': 1,
  'time': 60,
  'age': 28,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 70,
  'income': 245,
  'assets': 0,
  'debt': 0,
  'amount': 1830,
  'price': 2201},
 {'status': 1,
  'seniority': 8,
  'home': 1,
  'time': 48,
  'age': 31,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 90,
  'income': 150,
  'assets': 0,
  'debt': 0,
  'amount': 1100,
  'price': 1430},
 {'status': 2,
  'seniority': 4,
  'home': 5,
  'time': 42,
  'age': 27,
  'marital': 1,
  'records': 1,
  'job': 1,
  'expenses': 35,
  'income': 70,
  'assets': 0,
  'debt': 0,
  'amount': 600,
  'price': 926},
 {'status': 1,
  'seniority': 22,
  'home': 2,
  'time': 24,
  'age': 40,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 190,
  'assets': 3000,
  'debt': 0,
  'amount': 1000,
  'price': 1500},
 {'status': 1,
  'seniority': 2,
  'home': 2,
  'time': 36,
  'age': 35,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 152,
  'assets': 3000,
  'debt': 0,
  'amount': 1000,
  'price': 1542},
 {'status': 1,
  'seniority': 15,
  'home': 3,
  'time': 60,
  'age': 43,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 126,
  'assets': 3000,
  'debt': 0,
  'amount': 1350,
  'price': 1360},
 {'status': 1,
  'seniority': 10,
  'home': 2,
  'time': 18,
  'age': 34,
  'marital': 2,
  'records': 1,
  'job': 3,
  'expenses': 75,
  'income': 181,
  'assets': 4000,
  'debt': 0,
  'amount': 600,
  'price': 1000},
 {'status': 1,
  'seniority': 4,
  'home': 2,
  'time': 60,
  'age': 37,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 60,
  'income': 185,
  'assets': 3000,
  'debt': 0,
  'amount': 1200,
  'price': 1564},
 {'status': 1,
  'seniority': 9,
  'home': 2,
  'time': 60,
  'age': 53,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 45,
  'income': 170,
  'assets': 2500,
  'debt': 0,
  'amount': 850,
  'price': 1205},
 {'status': 1,
  'seniority': 22,
  'home': 1,
  'time': 60,
  'age': 46,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 93,
  'income': 176,
  'assets': 7500,
  'debt': 0,
  'amount': 2000,
  'price': 2200},
 {'status': 1,
  'seniority': 18,
  'home': 5,
  'time': 36,
  'age': 36,
  'marital': 2,
  'records': 1,
  'job': 3,
  'expenses': 60,
  'income': 238,
  'assets': 0,
  'debt': 0,
  'amount': 900,
  'price': 2214},
 {'status': 1,
  'seniority': 1,
  'home': 3,
  'time': 60,
  'age': 46,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 60,
  'income': 115,
  'assets': 5500,
  'debt': 800,
  'amount': 1000,
  'price': 1137},
 {'status': 1,
  'seniority': 14,
  'home': 2,
  'time': 48,
  'age': 43,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 45,
  'income': 200,
  'assets': 9000,
  'debt': 0,
  'amount': 600,
  'price': 1025},
 {'status': 1,
  'seniority': 8,
  'home': 2,
  'time': 36,
  'age': 31,
  'marital': 2,
  'records': 2,
  'job': 3,
  'expenses': 75,
  'income': 411,
  'assets': 9000,
  'debt': 4000,
  'amount': 800,
  'price': 1593},
 {'status': 1,
  'seniority': 5,
  'home': 2,
  'time': 24,
  'age': 43,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 93,
  'assets': 3000,
  'debt': 0,
  'amount': 700,
  'price': 1735},
 {'status': 1,
  'seniority': 19,
  'home': 1,
  'time': 60,
  'age': 38,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 86,
  'income': 108,
  'assets': 0,
  'debt': 0,
  'amount': 1000,
  'price': 1132},
 {'status': 1,
  'seniority': 14,
  'home': 2,
  'time': 12,
  'age': 37,
  'marital': 2,
  'records': 1,
  'job': 3,
  'expenses': 90,
  'income': 500,
  'assets': 4000,
  'debt': 0,
  'amount': 500,
  'price': 1338},
 {'status': 1,
  'seniority': 0,
  'home': 6,
  'time': 36,
  'age': 46,
  'marital': 2,
  'records': 2,
  'job': 4,
  'expenses': 45,
  'income': 45,
  'assets': 0,
  'debt': 0,
  'amount': 900,
  'price': 1100},
 {'status': 1,
  'seniority': 9,
  'home': 1,
  'time': 36,
  'age': 55,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 70,
  'income': 250,
  'assets': 30000,
  'debt': 0,
  'amount': 1750,
  'price': 2276},
 {'status': 1,
  'seniority': 29,
  'home': 2,
  'time': 48,
  'age': 56,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 45,
  'income': 100,
  'assets': 3000,
  'debt': 0,
  'amount': 900,
  'price': 1360},
 {'status': 1,
  'seniority': 10,
  'home': 2,
  'time': 36,
  'age': 55,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 60,
  'income': 70,
  'assets': 4000,
  'debt': 0,
  'amount': 1000,
  'price': 1436},
 {'status': 1,
  'seniority': 10,
  'home': 5,
  'time': 36,
  'age': 52,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 60,
  'income': 150,
  'assets': 0,
  'debt': 0,
  'amount': 550,
  'price': 612},
 {'status': 2,
  'seniority': 1,
  'home': 2,
  'time': 36,
  'age': 29,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 60,
  'income': 70,
  'assets': 4500,
  'debt': 0,
  'amount': 850,
  'price': 1100},
 {'status': 1,
  'seniority': 11,
  'home': 2,
  'time': 60,
  'age': 39,
  'marital': 5,
  'records': 2,
  'job': 1,
  'expenses': 35,
  'income': 263,
  'assets': 2500,
  'debt': 0,
  'amount': 1000,
  'price': 1300},
 {'status': 1,
  'seniority': 10,
  'home': 2,
  'time': 60,
  'age': 38,
  'marital': 2,
  'records': 1,
  'job': 3,
  'expenses': 75,
  'income': 200,
  'assets': 9000,
  'debt': 0,
  'amount': 1000,
  'price': 2089},
 {'status': 1,
  'seniority': 5,
  'home': 2,
  'time': 24,
  'age': 24,
  'marital': 1,
  'records': 1,
  'job': 1,
  'expenses': 35,
  'income': 78,
  'assets': 6000,
  'debt': 3000,
  'amount': 500,
  'price': 2262},
 {'status': 1,
  'seniority': 10,
  'home': 1,
  'time': 60,
  'age': 28,
  'marital': 1,
  'records': 1,
  'job': 1,
  'expenses': 47,
  'income': 120,
  'assets': 0,
  'debt': 0,
  'amount': 600,
  'price': 1054},
 {'status': 1,
  'seniority': 27,
  'home': 2,
  'time': 60,
  'age': 53,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 60,
  'income': 125,
  'assets': 10000,
  'debt': 0,
  'amount': 1426,
  'price': 1426},
 {'status': 2,
  'seniority': 0,
  'home': 1,
  'time': 60,
  'age': 25,
  'marital': 1,
  'records': 1,
  'job': 2,
  'expenses': 40,
  'income': 50,
  'assets': 0,
  'debt': 0,
  'amount': 1040,
  'price': 1048},
 {'status': 2,
  'seniority': 25,
  'home': 1,
  'time': 60,
  'age': 62,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 60,
  'income': 146,
  'assets': 0,
  'debt': 0,
  'amount': 1000,
  'price': 1292},
 {'status': 1,
  'seniority': 3,
  'home': 5,
  'time': 60,
  'age': 29,
  'marital': 1,
  'records': 1,
  'job': 1,
  'expenses': 35,
  'income': 70,
  'assets': 0,
  'debt': 0,
  'amount': 950,
  'price': 1177},
 {'status': 2,
  'seniority': 9,
  'home': 5,
  'time': 60,
  'age': 32,
  'marital': 1,
  'records': 2,
  'job': 1,

In [ ]:
import pymongo

'''
Cluster
   ↓
Database
   ↓
Collection
   ↓
Document
'''

# Variables required for storing data on MongoDB
DB_NAME = "Credit_Scoring_Database"
COLLECTION_NAME = "credit_scoring_data"
CONNECTION_URL = ""

In [ ]:
# Posting data at MongoDb

client = pymongo.MongoClient(CONNECTION_URL)
data_base = client[DB_NAME]
collection = data_base[COLLECTION_NAME]

rec = collection.insert_many(data)

In [102]:
# Faetching records from MongoDB and analyzing/processing the recodrs 
records = collection.find()
records

In [103]:
for i, j in enumerate(records):
    print(f"{i}: {j}")

0: {'_id': ObjectId('69bbae32b0c8809709d7435a'), 'status': 1, 'seniority': 9, 'home': 1, 'time': 60, 'age': 30, 'marital': 2, 'records': 1, 'job': 3, 'expenses': 73, 'income': 129, 'assets': 0, 'debt': 0, 'amount': 800, 'price': 846}
1: {'_id': ObjectId('69bbae32b0c8809709d7435b'), 'status': 1, 'seniority': 17, 'home': 1, 'time': 60, 'age': 58, 'marital': 3, 'records': 1, 'job': 1, 'expenses': 48, 'income': 131, 'assets': 0, 'debt': 0, 'amount': 1000, 'price': 1658}
2: {'_id': ObjectId('69bbae32b0c8809709d7435c'), 'status': 2, 'seniority': 10, 'home': 2, 'time': 36, 'age': 46, 'marital': 2, 'records': 2, 'job': 3, 'expenses': 90, 'income': 200, 'assets': 3000, 'debt': 0, 'amount': 2000, 'price': 2985}
3: {'_id': ObjectId('69bbae32b0c8809709d7435d'), 'status': 1, 'seniority': 0, 'home': 1, 'time': 60, 'age': 24, 'marital': 1, 'records': 1, 'job': 1, 'expenses': 63, 'income': 182, 'assets': 2500, 'debt': 0, 'amount': 900, 'price': 1325}
4: {'_id': ObjectId('69bbae32b0c8809709d7435e'), 'status': 1, 'seniority': 0, 'home': 1, 'time': 36, 'age': 26, 'marital': 1, 'records': 1, 'job': 1, 'expenses': 46, 'income': 107, 'assets': 0, 'debt': 0, 'amount': 310, 'price': 910}
5: {'_id': ObjectId('69bbae32b0c8809709d7435f'), 'status': 1, 'seniority': 1, 'home': 2, 'time': 60, 'age': 36, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 75, 'income': 214, 'assets': 3500, 'debt': 0, 'amount': 650, 'price': 1645}
6: {'_id': ObjectId('69bbae32b0c8809709d74360'), 'status': 1, 'seniority': 29, 'home': 2, 'time': 60, 'age': 44, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 75, 'income': 125, 'assets': 10000, 'debt': 0, 'amount': 1600, 'price': 1800}
7: {'_id': ObjectId('69bbae32b0c8809709d74361'), 'status': 1, 'seniority': 9, 'home': 5, 'time': 12, 'age': 27, 'marital': 1, 'records': 1, 'job': 1, 'expenses': 35, 'income': 80, 'assets': 0, 'debt': 0, 'amount': 200, 'price': 1093}
8: {'_id': ObjectId('69bbae32b0c8809709d74362'), 'status': 1, 'seniority': 0, 'home': 2, 'time': 60, 'age': 32, 'marital': 2, 'records': 1, 'job': 3, 'expenses': 90, 'income': 107, 'assets': 15000, 'debt': 0, 'amount': 1200, 'price': 1957}
9: {'_id': ObjectId('69bbae32b0c8809709d74363'), 'status': 2, 'seniority': 0, 'home': 5, 'time': 48, 'age': 41, 'marital': 2, 'records': 1, 'job': 2, 'expenses': 90, 'income': 80, 'assets': 0, 'debt': 0, 'amount': 1200, 'price': 1468}
10: {'_id': ObjectId('69bbae32b0c8809709d74364'), 'status': 1, 'seniority': 6, 'home': 2, 'time': 48, 'age': 34, 'marital': 2, 'records': 1, 'job': 3, 'expenses': 60, 'income': 125, 'assets': 4000, 'debt': 0, 'amount': 1150, 'price': 1577}
11: {'_id': ObjectId('69bbae32b0c8809709d74365'), 'status': 1, 'seniority': 7, 'home': 2, 'time': 36, 'age': 29, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 60, 'income': 121, 'assets': 3000, 'debt': 0, 'amount': 650, 'price': 915}
12: {'_id': ObjectId('69bbae32b0c8809709d74366'), 'status': 1, 'seniority': 8, 'home': 2, 'time': 60, 'age': 30, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 75, 'income': 199, 'assets': 5000, 'debt': 2500, 'amount': 1500, 'price': 1650}
13: {'_id': ObjectId('69bbae32b0c8809709d74367'), 'status': 1, 'seniority': 19, 'home': 3, 'time': 36, 'age': 37, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 75, 'income': 170, 'assets': 3500, 'debt': 260, 'amount': 600, 'price': 940}
14: {'_id': ObjectId('69bbae32b0c8809709d74368'), 'status': 2, 'seniority': 0, 'home': 6, 'time': 18, 'age': 21, 'marital': 1, 'records': 2, 'job': 2, 'expenses': 35, 'income': 50, 'assets': 0, 'debt': 0, 'amount': 400, 'price': 500}
15: {'_id': ObjectId('69bbae32b0c8809709d74369'), 'status': 1, 'seniority': 0, 'home': 2, 'time': 24, 'age': 68, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 75, 'income': 131, 'assets': 4162, 'debt': 0, 'amount': 900, 'price': 1186}
16: {'_id': ObjectId('69bbae32b0c8809709d7436a'), 'status': 1, 'seniority': 15, 'home': 3, 'time': 24, 'age': 52, 'marital': 1, 'records': 1, 'job': 3, 'expenses': 35, 'income': 330, 'assets': 16500, 'debt': 0, 'amount': 1500, 'price': 2201}
17: {'_id': ObjectId('69bbae32b0c8809709d7436b'), 'status': 1, 'seniority': 33, 'home': 1, 'time': 24, 'age': 68, 'marital': 2, 'records': 1, 'job': 3, 'expenses': 65, 'income': 200, 'assets': 5000, 'debt': 2000, 'amount': 600, 'price': 1350}
18: {'_id': ObjectId('69bbae32b0c8809709d7436c'), 'status': 2, 'seniority': 0, 'home': 4, 'time': 48, 'age': 36, 'marital': 2, 'records': 1, 'job': 2, 'expenses': 45, 'income': 130, 'assets': 750, 'debt': 0, 'amount': 1100, 'price': 1511}
19: {'_id': ObjectId('69bbae32b0c8809709d7436d'), 'status': 1, 'seniority': 1, 'home': 5, 'time': 60, 'age': 31, 'marital': 1, 'records': 1, 'job': 1, 'expenses': 35, 'income': 137, 'assets': 0, 'debt': 0, 'amount': 1250, 'price': 1253}
20: {'_id': ObjectId('69bbae32b0c8809709d7436e'), 'status': 2, 'seniority': 2, 'home': 1, 'time': 60, 'age': 25, 'marital': 1, 'records': 1, 'job': 1, 'expenses': 46, 'income': 107, 'assets': 0, 'debt': 0, 'amount': 1500, 'price': 2189}
21: {'_id': ObjectId('69bbae32b0c8809709d7436f'), 'status': 1, 'seniority': 5, 'home': 2, 'time': 60, 'age': 22, 'marital': 1, 'records': 1, 'job': 1, 'expenses': 45, 'income': 324, 'assets': 10000, 'debt': 0, 'amount': 1100, 'price': 1159}
22: {'_id': ObjectId('69bbae32b0c8809709d74370'), 'status': 2, 'seniority': 1, 'home': 2, 'time': 60, 'age': 45, 'marital': 2, 'records': 1, 'job': 2, 'expenses': 105, 'income': 112, 'assets': 2000, 'debt': 500, 'amount': 600, 'price': 1332}
23: {'_id': ObjectId('69bbae32b0c8809709d74371'), 'status': 1, 'seniority': 27, 'home': 1, 'time': 60, 'age': 41, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 74, 'income': 140, 'assets': 0, 'debt': 0, 'amount': 950, 'price': 1497}
24: {'_id': ObjectId('69bbae32b0c8809709d74372'), 'status': 1, 'seniority': 26, 'home': 2, 'time': 60, 'age': 51, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 45, 'income': 143, 'assets': 3500, 'debt': 0, 'amount': 1350, 'price': 1357}
25: {'_id': ObjectId('69bbae32b0c8809709d74373'), 'status': 1, 'seniority': 12, 'home': 2, 'time': 36, 'age': 54, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 60, 'income': 130, 'assets': 4000, 'debt': 0, 'amount': 700, 'price': 2100}
26: {'_id': ObjectId('69bbae32b0c8809709d74374'), 'status': 1, 'seniority': 19, 'home': 2, 'time': 60, 'age': 43, 'marital': 1, 'records': 1, 'job': 1, 'expenses': 75, 'income': 180, 'assets': 4000, 'debt': 0, 'amount': 1000, 'price': 1070}
27: {'_id': ObjectId('69bbae32b0c8809709d74375'), 'status': 1, 'seniority': 15, 'home': 2, 'time': 36, 'age': 43, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 75, 'income': 251, 'assets': 4000, 'debt': 0, 'amount': 1800, 'price': 2557}
28: {'_id': ObjectId('69bbae32b0c8809709d74376'), 'status': 2, 'seniority': 3, 'home': 2, 'time': 24, 'age': 23, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 75, 'income': 85, 'assets': 5000, 'debt': 0, 'amount': 600, 'price': 1600}
29: {'_id': ObjectId('69bbae32b0c8809709d74377'), 'status': 2, 'seniority': 0, 'home': 0, 'time': 48, 'age': 37, 'marital': 1, 'records': 1, 'job': 0, 'expenses': 35, 'income': 99999999, 'assets': 99999999, 'debt': 99999999, 'amount': 1500, 'price': 1850}
30: {'_id': ObjectId('69bbae32b0c8809709d74378'), 'status': 1, 'seniority': 4, 'home': 2, 'time': 48, 'age': 29, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 45, 'income': 150, 'assets': 5000, 'debt': 3300, 'amount': 1100, 'price': 1312}
31: {'_id': ObjectId('69bbae32b0c8809709d74379'), 'status': 2, 'seniority': 0, 'home': 2, 'time': 36, 'age': 23, 'marital': 1, 'records': 1, 'job': 2, 'expenses': 45, 'income': 122, 'assets': 2500, 'debt': 0, 'amount': 400, 'price': 400}
32: {'_id': ObjectId('69bbae32b0c8809709d7437a'), 'status': 1, 'seniority': 14, 'home': 3, 'time': 24, 'age': 51, 'marital': 2, 'records': 1, 'job': 2, 'expenses': 75, 'income': 198, 'assets': 1000, 'debt': 0, 'amount': 450, 'price': 650}
33: {'_id': ObjectId('69bbae32b0c8809709d7437b'), 'status': 1, 'seniority': 10, 'home': 2, 'time': 36, 'age': 39, 'marital': 2, 'records': 1, 'job': 3, 'expenses': 75, 'income': 150, 'assets': 3000, 'debt': 0, 'amount': 1000, 'price': 1394}
34: {'_id': ObjectId('69bbae32b0c8809709d7437c'), 'status': 1, 'seniority': 12, 'home': 5, 'time': 36, 'age': 35, 'marital': 1, 'records': 1, 'job': 1, 'expenses': 35, 'income': 170, 'assets': 0, 'debt': 0, 'amount': 1100, 'price': 1542}
35: {'_id': ObjectId('69bbae32b0c8809709d7437d'), 'status': 1, 'seniority': 32, 'home': 2, 'time': 24, 'age': 62, 'marital': 2, 'records': 1, 'job': 3, 'expenses': 45, 'income': 119, 'assets': 8500, 'debt': 0, 'amount': 700, 'price': 1200}
36: {'_id': ObjectId('69bbae32b0c8809709d7437e'), 'status': 1, 'seniority': 10, 'home': 2, 'time': 24, 'age': 56, 'marital': 2, 'records': 1, 'job': 3, 'expenses': 45, 'income': 208, 'assets': 13500, 'debt': 0, 'amount': 500, 'price': 1560}
37: {'_id': ObjectId('69bbae32b0c8809709d7437f'), 'status': 1, 'seniority': 7, 'home': 2, 'time': 48, 'age': 32, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 75, 'income': 115, 'assets': 3000, 'debt': 0, 'amount': 800, 'price': 1200}
38: {'_id': ObjectId('69bbae32b0c8809709d74380'), 'status': 2, 'seniority': 1, 'home': 1, 'time': 54, 'age': 36, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 70, 'income': 99, 'assets': 0, 'debt': 0, 'amount': 950, 'price': 950}
39: {'_id': ObjectId('69bbae32b0c8809709d74381'), 'status': 1, 'seniority': 30, 'home': 2, 'time': 60, 'age': 64, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 45, 'income': 120, 'assets': 14000, 'debt': 0, 'amount': 1125, 'price': 1300}
40: {'_id': ObjectId('69bbae32b0c8809709d74382'), 'status': 2, 'seniority': 5, 'home': 1, 'time': 48, 'age': 31, 'marital': 1, 'records': 1, 'job': 1, 'expenses': 44, 'income': 90, 'assets': 0, 'debt': 0, 'amount': 1300, 'price': 1700}
41: {'_id': ObjectId('69bbae32b0c8809709d74383'), 'status': 1, 'seniority': 24, 'home': 2, 'time': 60, 'age': 42, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 75, 'income': 137, 'assets': 4000, 'debt': 0, 'amount': 900, 'price': 1167}
42: {'_id': ObjectId('69bbae32b0c8809709d74384'), 'status': 1, 'seniority': 0, 'home': 2, 'time': 60, 'age': 61, 'marital': 3, 'records': 1, 'job': 4, 'expenses': 35, 'income': 230, 'assets': 50000, 'debt': 0, 'amount': 950, 'price': 1150}
43: {'_id': ObjectId('69bbae32b0c8809709d74385'), 'status': 2, 'seniority': 0, 'home': 2, 'time': 60, 'age': 32, 'marital': 2, 'records': 2, 'job': 1, 'expenses': 45, 'income': 142, 'assets': 7000, 'debt': 3000, 'amount': 1250, 'price': 1566}
44: {'_id': ObjectId('69bbae32b0c8809709d74386'), 'status': 2, 'seniority': 2, 'home': 2, 'time': 60, 'age': 43, 'marital': 2, 'records': 1, 'job': 2, 'expenses': 75, 'income': 71, 'assets': 3000, 'debt': 0, 'amount': 1500, 'price': 1552}
45: {'_id': ObjectId('69bbae32b0c8809709d74387'), 'status': 1, 'seniority': 1, 'home': 5, 'time': 60, 'age': 26, 'marital': 1, 'records': 1, 'job': 2, 'expenses': 35, 'income': 120, 'assets': 0, 'debt': 0, 'amount': 1150, 'price': 1300}
46: {'_id': ObjectId('69bbae32b0c8809709d74388'), 'status': 1, 'seniority': 1, 'home': 2, 'time': 60, 'age': 49, 'marital': 3, 'records': 1, 'job': 3, 'expenses': 35, 'income': 233, 'assets': 15900, 'debt': 4500, 'amount': 2100, 'price': 2104}
47: {'_id': ObjectId('69bbae32b0c8809709d74389'), 'status': 1, 'seniority': 15, 'home': 2, 'time': 36, 'age': 47, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 75, 'income': 289, 'assets': 3500, 'debt': 0, 'amount': 1500, 'price': 2154}
48: {'_id': ObjectId('69bbae32b0c8809709d7438a'), 'status': 2, 'seniority': 2, 'home': 1, 'time': 36, 'age': 27, 'marital': 4, 'records': 1, 'job': 1, 'expenses': 48, 'income': 128, 'assets': 0, 'debt': 0, 'amount': 450, 'price': 545}
49: {'_id': ObjectId('69bbae32b0c8809709d7438b'), 'status': 1, 'seniority': 25, 'home': 2, 'time': 36, 'age': 52, 'marital': 2, 'records': 1, 'job': 3, 'expenses': 60, 'income': 150, 'assets': 15000, 'debt': 0, 'amount': 750, 'price': 1778}
50: {'_id': ObjectId('69bbae32b0c8809709d7438c'), 'status': 1, 'seniority': 8, 'home': 2, 'time': 60, 'age': 28, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 60, 'income': 145, 'assets': 4000, 'debt': 1000, 'amount': 1600, 'price': 1718}
51: {'_id': ObjectId('69bbae32b0c8809709d7438d'), 'status': 1, 'seniority': 5, 'home': 2, 'time': 60, 'age': 31, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 75, 'income': 90, 'assets': 4000, 'debt': 0, 'amount': 900, 'price': 1500}
52: {'_id': ObjectId('69bbae32b0c8809709d7438e'), 'status': 1, 'seniority': 0, 'home': 1, 'time': 60, 'age': 32, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 105, 'income': 301, 'assets': 0, 'debt': 0, 'amount': 1200, 'price': 1274}
53: {'_id': ObjectId('69bbae32b0c8809709d7438f'), 'status': 1, 'seniority': 5, 'home': 2, 'time': 36, 'age': 51, 'marital': 2, 'records': 1, 'job': 3, 'expenses': 75, 'income': 200, 'assets': 2100, 'debt': 1200, 'amount': 900, 'price': 1015}
54: {'_id': ObjectId('69bbae32b0c8809709d74390'), 'status': 1, 'seniority': 3, 'home': 5, 'time': 12, 'age': 37, 'marital': 2, 'records': 1, 'job': 3, 'expenses': 60, 'income': 150, 'assets': 500, 'debt': 0, 'amount': 500, 'price': 1701}
55: {'_id': ObjectId('69bbae32b0c8809709d74391'), 'status': 2, 'seniority': 1, 'home': 1, 'time': 48, 'age': 29, 'marital': 2, 'records': 2, 'job': 3, 'expenses': 85, 'income': 100, 'assets': 0, 'debt': 0, 'amount': 1000, 'price': 1345}
56: {'_id': ObjectId('69bbae32b0c8809709d74392'), 'status': 1, 'seniority': 7, 'home': 5, 'time': 60, 'age': 26, 'marital': 1, 'records': 1, 'job': 1, 'expenses': 35, 'income': 100, 'assets': 0, 'debt': 0, 'amount': 1000, 'price': 1238}
57: {'_id': ObjectId('69bbae32b0c8809709d74393'), 'status': 1, 'seniority': 4, 'home': 5, 'time': 30, 'age': 27, 'marital': 1, 'records': 1, 'job': 1, 'expenses': 45, 'income': 100, 'assets': 5000, 'debt': 0, 'amount': 500, 'price': 1048}
58: {'_id': ObjectId('69bbae32b0c8809709d74394'), 'status': 1, 'seniority': 6, 'home': 2, 'time': 24, 'age': 63, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 60, 'income': 155, 'assets': 4000, 'debt': 0, 'amount': 600, 'price': 1048}
59: {'_id': ObjectId('69bbae32b0c8809709d74395'), 'status': 1, 'seniority': 14, 'home': 2, 'time': 24, 'age': 55, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 90, 'income': 715, 'assets': 5000, 'debt': 0, 'amount': 800, 'price': 1324}
60: {'_id': ObjectId('69bbae32b0c8809709d74396'), 'status': 1, 'seniority': 3, 'home': 1, 'time': 60, 'age': 28, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 70, 'income': 245, 'assets': 0, 'debt': 0, 'amount': 1830, 'price': 2201}
61: {'_id': ObjectId('69bbae32b0c8809709d74397'), 'status': 1, 'seniority': 8, 'home': 1, 'time': 48, 'age': 31, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 90, 'income': 150, 'assets': 0, 'debt': 0, 'amount': 1100, 'price': 1430}
62: {'_id': ObjectId('69bbae32b0c8809709d74398'), 'status': 2, 'seniority': 4, 'home': 5, 'time': 42, 'age': 27, 'marital': 1, 'records': 1, 'job': 1, 'expenses': 35, 'income': 70, 'assets': 0, 'debt': 0, 'amount': 600, 'price': 926}
63: {'_id': ObjectId('69bbae32b0c8809709d74399'), 'status': 1, 'seniority': 22, 'home': 2, 'time': 24, 'age': 40, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 75, 'income': 190, 'assets': 3000, 'debt': 0, 'amount': 1000, 'price': 1500}
64: {'_id': ObjectId('69bbae32b0c8809709d7439a'), 'status': 1, 'seniority': 2, 'home': 2, 'time': 36, 'age': 35, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 75, 'income': 152, 'assets': 3000, 'debt': 0, 'amount': 1000, 'price': 1542}
65: {'_id': ObjectId('69bbae32b0c8809709d7439b'), 'status': 1, 'seniority': 15, 'home': 3, 'time': 60, 'age': 43, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 75, 'income': 126, 'assets': 3000, 'debt': 0, 'amount': 1350, 'price': 1360}
66: {'_id': ObjectId('69bbae32b0c8809709d7439c'), 'status': 1, 'seniority': 10, 'home': 2, 'time': 18, 'age': 34, 'marital': 2, 'records': 1, 'job': 3, 'expenses': 75, 'income': 181, 'assets': 4000, 'debt': 0, 'amount': 600, 'price': 1000}
67: {'_id': ObjectId('69bbae32b0c8809709d7439d'), 'status': 1, 'seniority': 4, 'home': 2, 'time': 60, 'age': 37, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 60, 'income': 185, 'assets': 3000, 'debt': 0, 'amount': 1200, 'price': 1564}
68: {'_id': ObjectId('69bbae32b0c8809709d7439e'), 'status': 1, 'seniority': 9, 'home': 2, 'time': 60, 'age': 53, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 45, 'income': 170, 'assets': 2500, 'debt': 0, 'amount': 850, 'price': 1205}
69: {'_id': ObjectId('69bbae32b0c8809709d7439f'), 'status': 1, 'seniority': 22, 'home': 1, 'time': 60, 'age': 46, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 93, 'income': 176, 'assets': 7500, 'debt': 0, 'amount': 2000, 'price': 2200}
70: {'_id': ObjectId('69bbae32b0c8809709d743a0'), 'status': 1, 'seniority': 18, 'home': 5, 'time': 36, 'age': 36, 'marital': 2, 'records': 1, 'job': 3, 'expenses': 60, 'income': 238, 'assets': 0, 'debt': 0, 'amount': 900, 'price': 2214}
71: {'_id': ObjectId('69bbae32b0c8809709d743a1'), 'status': 1, 'seniority': 1, 'home': 3, 'time': 60, 'age': 46, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 60, 'income': 115, 'assets': 5500, 'debt': 800, 'amount': 1000, 'price': 1137}
72: {'_id': ObjectId('69bbae32b0c8809709d743a2'), 'status': 1, 'seniority': 14, 'home': 2, 'time': 48, 'age': 43, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 45, 'income': 200, 'assets': 9000, 'debt': 0, 'amount': 600, 'price': 1025}
73: {'_id': ObjectId('69bbae32b0c8809709d743a3'), 'status': 1, 'seniority': 8, 'home': 2, 'time': 36, 'age': 31, 'marital': 2, 'records': 2, 'job': 3, 'expenses': 75, 'income': 411, 'assets': 9000, 'debt': 4000, 'amount': 800, 'price': 1593}
74: {'_id': ObjectId('69bbae32b0c8809709d743a4'), 'status': 1, 'seniority': 5, 'home': 2, 'time': 24, 'age': 43, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 75, 'income': 93, 'assets': 3000, 'debt': 0, 'amount': 700, 'price': 1735}
75: {'_id': ObjectId('69bbae32b0c8809709d743a5'), 'status': 1, 'seniority': 19, 'home': 1, 'time': 60, 'age': 38, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 86, 'income': 108, 'assets': 0, 'debt': 0, 'amount': 1000, 'price': 1132}
76: {'_id': ObjectId('69bbae32b0c8809709d743a6'), 'status': 1, 'seniority': 14, 'home': 2, 'time': 12, 'age': 37, 'marital': 2, 'records': 1, 'job': 3, 'expenses': 90, 'income': 500, 'assets': 4000, 'debt': 0, 'amount': 500, 'price': 1338}
77: {'_id': ObjectId('69bbae32b0c8809709d743a7'), 'status': 1, 'seniority': 0, 'home': 6, 'time': 36, 'age': 46, 'marital': 2, 'records': 2, 'job': 4, 'expenses': 45, 'income': 45, 'assets': 0, 'debt': 0, 'amount': 900, 'price': 1100}
78: {'_id': ObjectId('69bbae32b0c8809709d743a8'), 'status': 1, 'seniority': 9, 'home': 1, 'time': 36, 'age': 55, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 70, 'income': 250, 'assets': 30000, 'debt': 0, 'amount': 1750, 'price': 2276}
79: {'_id': ObjectId('69bbae32b0c8809709d743a9'), 'status': 1, 'seniority': 29, 'home': 2, 'time': 48, 'age': 56, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 45, 'income': 100, 'assets': 3000, 'debt': 0, 'amount': 900, 'price': 1360}
80: {'_id': ObjectId('69bbae32b0c8809709d743aa'), 'status': 1, 'seniority': 10, 'home': 2, 'time': 36, 'age': 55, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 60, 'income': 70, 'assets': 4000, 'debt': 0, 'amount': 1000, 'price': 1436}
81: {'_id': ObjectId('69bbae32b0c8809709d743ab'), 'status': 1, 'seniority': 10, 'home': 5, 'time': 36, 'age': 52, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 60, 'income': 150, 'assets': 0, 'debt': 0, 'amount': 550, 'price': 612}
82: {'_id': ObjectId('69bbae32b0c8809709d743ac'), 'status': 2, 'seniority': 1, 'home': 2, 'time': 36, 'age': 29, 'marital': 2, 'records': 1, 'job': 1, 'expenses': 60, 'income': 70, 'assets': 4500, 'debt': 0, 'amount': 850, 'price': 1100}

In [104]:
collection.find()

In [105]:
list(collection.find())

[{'_id': ObjectId('69bbae32b0c8809709d7435a'),
  'status': 1,
  'seniority': 9,
  'home': 1,
  'time': 60,
  'age': 30,
  'marital': 2,
  'records': 1,
  'job': 3,
  'expenses': 73,
  'income': 129,
  'assets': 0,
  'debt': 0,
  'amount': 800,
  'price': 846},
 {'_id': ObjectId('69bbae32b0c8809709d7435b'),
  'status': 1,
  'seniority': 17,
  'home': 1,
  'time': 60,
  'age': 58,
  'marital': 3,
  'records': 1,
  'job': 1,
  'expenses': 48,
  'income': 131,
  'assets': 0,
  'debt': 0,
  'amount': 1000,
  'price': 1658},
 {'_id': ObjectId('69bbae32b0c8809709d7435c'),
  'status': 2,
  'seniority': 10,
  'home': 2,
  'time': 36,
  'age': 46,
  'marital': 2,
  'records': 2,
  'job': 3,
  'expenses': 90,
  'income': 200,
  'assets': 3000,
  'debt': 0,
  'amount': 2000,
  'price': 2985},
 {'_id': ObjectId('69bbae32b0c8809709d7435d'),
  'status': 1,
  'seniority': 0,
  'home': 1,
  'time': 60,
  'age': 24,
  'marital': 1,
  'records': 1,
  'job': 1,
  'expenses': 63,
  'income': 182,
  'assets': 2500,
  'debt': 0,
  'amount': 900,
  'price': 1325},
 {'_id': ObjectId('69bbae32b0c8809709d7435e'),
  'status': 1,
  'seniority': 0,
  'home': 1,
  'time': 36,
  'age': 26,
  'marital': 1,
  'records': 1,
  'job': 1,
  'expenses': 46,
  'income': 107,
  'assets': 0,
  'debt': 0,
  'amount': 310,
  'price': 910},
 {'_id': ObjectId('69bbae32b0c8809709d7435f'),
  'status': 1,
  'seniority': 1,
  'home': 2,
  'time': 60,
  'age': 36,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 214,
  'assets': 3500,
  'debt': 0,
  'amount': 650,
  'price': 1645},
 {'_id': ObjectId('69bbae32b0c8809709d74360'),
  'status': 1,
  'seniority': 29,
  'home': 2,
  'time': 60,
  'age': 44,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 125,
  'assets': 10000,
  'debt': 0,
  'amount': 1600,
  'price': 1800},
 {'_id': ObjectId('69bbae32b0c8809709d74361'),
  'status': 1,
  'seniority': 9,
  'home': 5,
  'time': 12,
  'age': 27,
  'marital': 1,
  'records': 1,
  'job': 1,
  'expenses': 35,
  'income': 80,
  'assets': 0,
  'debt': 0,
  'amount': 200,
  'price': 1093},
 {'_id': ObjectId('69bbae32b0c8809709d74362'),
  'status': 1,
  'seniority': 0,
  'home': 2,
  'time': 60,
  'age': 32,
  'marital': 2,
  'records': 1,
  'job': 3,
  'expenses': 90,
  'income': 107,
  'assets': 15000,
  'debt': 0,
  'amount': 1200,
  'price': 1957},
 {'_id': ObjectId('69bbae32b0c8809709d74363'),
  'status': 2,
  'seniority': 0,
  'home': 5,
  'time': 48,
  'age': 41,
  'marital': 2,
  'records': 1,
  'job': 2,
  'expenses': 90,
  'income': 80,
  'assets': 0,
  'debt': 0,
  'amount': 1200,
  'price': 1468},
 {'_id': ObjectId('69bbae32b0c8809709d74364'),
  'status': 1,
  'seniority': 6,
  'home': 2,
  'time': 48,
  'age': 34,
  'marital': 2,
  'records': 1,
  'job': 3,
  'expenses': 60,
  'income': 125,
  'assets': 4000,
  'debt': 0,
  'amount': 1150,
  'price': 1577},
 {'_id': ObjectId('69bbae32b0c8809709d74365'),
  'status': 1,
  'seniority': 7,
  'home': 2,
  'time': 36,
  'age': 29,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 60,
  'income': 121,
  'assets': 3000,
  'debt': 0,
  'amount': 650,
  'price': 915},
 {'_id': ObjectId('69bbae32b0c8809709d74366'),
  'status': 1,
  'seniority': 8,
  'home': 2,
  'time': 60,
  'age': 30,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 199,
  'assets': 5000,
  'debt': 2500,
  'amount': 1500,
  'price': 1650},
 {'_id': ObjectId('69bbae32b0c8809709d74367'),
  'status': 1,
  'seniority': 19,
  'home': 3,
  'time': 36,
  'age': 37,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 170,
  'assets': 3500,
  'debt': 260,
  'amount': 600,
  'price': 940},
 {'_id': ObjectId('69bbae32b0c8809709d74368'),
  'status': 2,
  'seniority': 0,
  'home': 6,
  'time': 18,
  'age': 21,
  'marital': 1,
  'records': 2,
  'job': 2,
  'expenses': 35,
  'income': 50,
  'assets': 0,
  'debt': 0,
  'amount': 400,
  'price': 500},
 {'_id': ObjectId('69bbae32b0c8809709d74369'),
  'status': 1,
  'seniority': 0,
  'home': 2,
  'time': 24,
  'age': 68,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 131,
  'assets': 4162,
  'debt': 0,
  'amount': 900,
  'price': 1186},
 {'_id': ObjectId('69bbae32b0c8809709d7436a'),
  'status': 1,
  'seniority': 15,
  'home': 3,
  'time': 24,
  'age': 52,
  'marital': 1,
  'records': 1,
  'job': 3,
  'expenses': 35,
  'income': 330,
  'assets': 16500,
  'debt': 0,
  'amount': 1500,
  'price': 2201},
 {'_id': ObjectId('69bbae32b0c8809709d7436b'),
  'status': 1,
  'seniority': 33,
  'home': 1,
  'time': 24,
  'age': 68,
  'marital': 2,
  'records': 1,
  'job': 3,
  'expenses': 65,
  'income': 200,
  'assets': 5000,
  'debt': 2000,
  'amount': 600,
  'price': 1350},
 {'_id': ObjectId('69bbae32b0c8809709d7436c'),
  'status': 2,
  'seniority': 0,
  'home': 4,
  'time': 48,
  'age': 36,
  'marital': 2,
  'records': 1,
  'job': 2,
  'expenses': 45,
  'income': 130,
  'assets': 750,
  'debt': 0,
  'amount': 1100,
  'price': 1511},
 {'_id': ObjectId('69bbae32b0c8809709d7436d'),
  'status': 1,
  'seniority': 1,
  'home': 5,
  'time': 60,
  'age': 31,
  'marital': 1,
  'records': 1,
  'job': 1,
  'expenses': 35,
  'income': 137,
  'assets': 0,
  'debt': 0,
  'amount': 1250,
  'price': 1253},
 {'_id': ObjectId('69bbae32b0c8809709d7436e'),
  'status': 2,
  'seniority': 2,
  'home': 1,
  'time': 60,
  'age': 25,
  'marital': 1,
  'records': 1,
  'job': 1,
  'expenses': 46,
  'income': 107,
  'assets': 0,
  'debt': 0,
  'amount': 1500,
  'price': 2189},
 {'_id': ObjectId('69bbae32b0c8809709d7436f'),
  'status': 1,
  'seniority': 5,
  'home': 2,
  'time': 60,
  'age': 22,
  'marital': 1,
  'records': 1,
  'job': 1,
  'expenses': 45,
  'income': 324,
  'assets': 10000,
  'debt': 0,
  'amount': 1100,
  'price': 1159},
 {'_id': ObjectId('69bbae32b0c8809709d74370'),
  'status': 2,
  'seniority': 1,
  'home': 2,
  'time': 60,
  'age': 45,
  'marital': 2,
  'records': 1,
  'job': 2,
  'expenses': 105,
  'income': 112,
  'assets': 2000,
  'debt': 500,
  'amount': 600,
  'price': 1332},
 {'_id': ObjectId('69bbae32b0c8809709d74371'),
  'status': 1,
  'seniority': 27,
  'home': 1,
  'time': 60,
  'age': 41,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 74,
  'income': 140,
  'assets': 0,
  'debt': 0,
  'amount': 950,
  'price': 1497},
 {'_id': ObjectId('69bbae32b0c8809709d74372'),
  'status': 1,
  'seniority': 26,
  'home': 2,
  'time': 60,
  'age': 51,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 45,
  'income': 143,
  'assets': 3500,
  'debt': 0,
  'amount': 1350,
  'price': 1357},
 {'_id': ObjectId('69bbae32b0c8809709d74373'),
  'status': 1,
  'seniority': 12,
  'home': 2,
  'time': 36,
  'age': 54,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 60,
  'income': 130,
  'assets': 4000,
  'debt': 0,
  'amount': 700,
  'price': 2100},
 {'_id': ObjectId('69bbae32b0c8809709d74374'),
  'status': 1,
  'seniority': 19,
  'home': 2,
  'time': 60,
  'age': 43,
  'marital': 1,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 180,
  'assets': 4000,
  'debt': 0,
  'amount': 1000,
  'price': 1070},
 {'_id': ObjectId('69bbae32b0c8809709d74375'),
  'status': 1,
  'seniority': 15,
  'home': 2,
  'time': 36,
  'age': 43,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 251,
  'assets': 4000,
  'debt': 0,
  'amount': 1800,
  'price': 2557},
 {'_id': ObjectId('69bbae32b0c8809709d74376'),
  'status': 2,
  'seniority': 3,
  'home': 2,
  'time': 24,
  'age': 23,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 85,
  'assets': 5000,
  'debt': 0,
  'amount': 600,
  'price': 1600},
 {'_id': ObjectId('69bbae32b0c8809709d74377'),
  'status': 2,
  'seniority': 0,
  'home': 0,
  'time': 48,
  'age': 37,
  'marital': 1,
  'records': 1,
  'job': 0,
  'expenses': 35,
  'income': 99999999,
  'assets': 99999999,
  'debt': 99999999,
  'amount': 1500,
  'price': 1850},
 {'_id': ObjectId('69bbae32b0c8809709d74378'),
  'status': 1,
  'seniority': 4,
  'home': 2,
  'time': 48,
  'age': 29,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 45,
  'income': 150,
  'assets': 5000,
  'debt': 3300,
  'amount': 1100,
  'price': 1312},
 {'_id': ObjectId('69bbae32b0c8809709d74379'),
  'status': 2,
  'seniority': 0,
  'home': 2,
  'time': 36,
  'age': 23,
  'marital': 1,
  'records': 1,
  'job': 2,
  'expenses': 45,
  'income': 122,
  'assets': 2500,
  'debt': 0,
  'amount': 400,
  'price': 400},
 {'_id': ObjectId('69bbae32b0c8809709d7437a'),
  'status': 1,
  'seniority': 14,
  'home': 3,
  'time': 24,
  'age': 51,
  'marital': 2,
  'records': 1,
  'job': 2,
  'expenses': 75,
  'income': 198,
  'assets': 1000,
  'debt': 0,
  'amount': 450,
  'price': 650},
 {'_id': ObjectId('69bbae32b0c8809709d7437b'),
  'status': 1,
  'seniority': 10,
  'home': 2,
  'time': 36,
  'age': 39,
  'marital': 2,
  'records': 1,
  'job': 3,
  'expenses': 75,
  'income': 150,
  'assets': 3000,
  'debt': 0,
  'amount': 1000,
  'price': 1394},
 {'_id': ObjectId('69bbae32b0c8809709d7437c'),
  'status': 1,
  'seniority': 12,
  'home': 5,
  'time': 36,
  'age': 35,
  'marital': 1,
  'records': 1,
  'job': 1,
  'expenses': 35,
  'income': 170,
  'assets': 0,
  'debt': 0,
  'amount': 1100,
  'price': 1542},
 {'_id': ObjectId('69bbae32b0c8809709d7437d'),
  'status': 1,
  'seniority': 32,
  'home': 2,
  'time': 24,
  'age': 62,
  'marital': 2,
  'records': 1,
  'job': 3,
  'expenses': 45,
  'income': 119,
  'assets': 8500,
  'debt': 0,
  'amount': 700,
  'price': 1200},
 {'_id': ObjectId('69bbae32b0c8809709d7437e'),
  'status': 1,
  'seniority': 10,
  'home': 2,
  'time': 24,
  'age': 56,
  'marital': 2,
  'records': 1,
  'job': 3,
  'expenses': 45,
  'income': 208,
  'assets': 13500,
  'debt': 0,
  'amount': 500,
  'price': 1560},
 {'_id': ObjectId('69bbae32b0c8809709d7437f'),
  'status': 1,
  'seniority': 7,
  'home': 2,
  'time': 48,
  'age': 32,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 115,
  'assets': 3000,
  'debt': 0,
  'amount': 800,
  'price': 1200},
 {'_id': ObjectId('69bbae32b0c8809709d74380'),
  'status': 2,
  'seniority': 1,
  'home': 1,
  'time': 54,
  'age': 36,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 70,
  'income': 99,
  'assets': 0,
  'debt': 0,
  'amount': 950,
  'price': 950},
 {'_id': ObjectId('69bbae32b0c8809709d74381'),
  'status': 1,
  'seniority': 30,
  'home': 2,
  'time': 60,
  'age': 64,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 45,
  'income': 120,
  'assets': 14000,
  'debt': 0,
  'amount': 1125,
  'price': 1300},
 {'_id': ObjectId('69bbae32b0c8809709d74382'),
  'status': 2,
  'seniority': 5,
  'home': 1,
  'time': 48,
  'age': 31,
  'marital': 1,
  'records': 1,
  'job': 1,
  'expenses': 44,
  'income': 90,
  'assets': 0,
  'debt': 0,
  'amount': 1300,
  'price': 1700},
 {'_id': ObjectId('69bbae32b0c8809709d74383'),
  'status': 1,
  'seniority': 24,
  'home': 2,
  'time': 60,
  'age': 42,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 137,
  'assets': 4000,
  'debt': 0,
  'amount': 900,
  'price': 1167},
 {'_id': ObjectId('69bbae32b0c8809709d74384'),
  'status': 1,
  'seniority': 0,
  'home': 2,
  'time': 60,
  'age': 61,
  'marital': 3,
  'records': 1,
  'job': 4,
  'expenses': 35,
  'income': 230,
  'assets': 50000,
  'debt': 0,
  'amount': 950,
  'price': 1150},
 {'_id': ObjectId('69bbae32b0c8809709d74385'),
  'status': 2,
  'seniority': 0,
  'home': 2,
  'time': 60,
  'age': 32,
  'marital': 2,
  'records': 2,
  'job': 1,
  'expenses': 45,
  'income': 142,
  'assets': 7000,
  'debt': 3000,
  'amount': 1250,
  'price': 1566},
 {'_id': ObjectId('69bbae32b0c8809709d74386'),
  'status': 2,
  'seniority': 2,
  'home': 2,
  'time': 60,
  'age': 43,
  'marital': 2,
  'records': 1,
  'job': 2,
  'expenses': 75,
  'income': 71,
  'assets': 3000,
  'debt': 0,
  'amount': 1500,
  'price': 1552},
 {'_id': ObjectId('69bbae32b0c8809709d74387'),
  'status': 1,
  'seniority': 1,
  'home': 5,
  'time': 60,
  'age': 26,
  'marital': 1,
  'records': 1,
  'job': 2,
  'expenses': 35,
  'income': 120,
  'assets': 0,
  'debt': 0,
  'amount': 1150,
  'price': 1300},
 {'_id': ObjectId('69bbae32b0c8809709d74388'),
  'status': 1,
  'seniority': 1,
  'home': 2,
  'time': 60,
  'age': 49,
  'marital': 3,
  'records': 1,
  'job': 3,
  'expenses': 35,
  'income': 233,
  'assets': 15900,
  'debt': 4500,
  'amount': 2100,
  'price': 2104},
 {'_id': ObjectId('69bbae32b0c8809709d74389'),
  'status': 1,
  'seniority': 15,
  'home': 2,
  'time': 36,
  'age': 47,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 289,
  'assets': 3500,
  'debt': 0,
  'amount': 1500,
  'price': 2154},
 {'_id': ObjectId('69bbae32b0c8809709d7438a'),
  'status': 2,
  'seniority': 2,
  'home': 1,
  'time': 36,
  'age': 27,
  'marital': 4,
  'records': 1,
  'job': 1,
  'expenses': 48,
  'income': 128,
  'assets': 0,
  'debt': 0,
  'amount': 450,
  'price': 545},
 {'_id': ObjectId('69bbae32b0c8809709d7438b'),
  'status': 1,
  'seniority': 25,
  'home': 2,
  'time': 36,
  'age': 52,
  'marital': 2,
  'records': 1,
  'job': 3,
  'expenses': 60,
  'income': 150,
  'assets': 15000,
  'debt': 0,
  'amount': 750,
  'price': 1778},
 {'_id': ObjectId('69bbae32b0c8809709d7438c'),
  'status': 1,
  'seniority': 8,
  'home': 2,
  'time': 60,
  'age': 28,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 60,
  'income': 145,
  'assets': 4000,
  'debt': 1000,
  'amount': 1600,
  'price': 1718},
 {'_id': ObjectId('69bbae32b0c8809709d7438d'),
  'status': 1,
  'seniority': 5,
  'home': 2,
  'time': 60,
  'age': 31,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 90,
  'assets': 4000,
  'debt': 0,
  'amount': 900,
  'price': 1500},
 {'_id': ObjectId('69bbae32b0c8809709d7438e'),
  'status': 1,
  'seniority': 0,
  'home': 1,
  'time': 60,
  'age': 32,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 105,
  'income': 301,
  'assets': 0,
  'debt': 0,
  'amount': 1200,
  'price': 1274},
 {'_id': ObjectId('69bbae32b0c8809709d7438f'),
  'status': 1,
  'seniority': 5,
  'home': 2,
  'time': 36,
  'age': 51,
  'marital': 2,
  'records': 1,
  'job': 3,
  'expenses': 75,
  'income': 200,
  'assets': 2100,
  'debt': 1200,
  'amount': 900,
  'price': 1015},
 {'_id': ObjectId('69bbae32b0c8809709d74390'),
  'status': 1,
  'seniority': 3,
  'home': 5,
  'time': 12,
  'age': 37,
  'marital': 2,
  'records': 1,
  'job': 3,
  'expenses': 60,
  'income': 150,
  'assets': 500,
  'debt': 0,
  'amount': 500,
  'price': 1701},
 {'_id': ObjectId('69bbae32b0c8809709d74391'),
  'status': 2,
  'seniority': 1,
  'home': 1,
  'time': 48,
  'age': 29,
  'marital': 2,
  'records': 2,
  'job': 3,
  'expenses': 85,
  'income': 100,
  'assets': 0,
  'debt': 0,
  'amount': 1000,
  'price': 1345},
 {'_id': ObjectId('69bbae32b0c8809709d74392'),
  'status': 1,
  'seniority': 7,
  'home': 5,
  'time': 60,
  'age': 26,
  'marital': 1,
  'records': 1,
  'job': 1,
  'expenses': 35,
  'income': 100,
  'assets': 0,
  'debt': 0,
  'amount': 1000,
  'price': 1238},
 {'_id': ObjectId('69bbae32b0c8809709d74393'),
  'status': 1,
  'seniority': 4,
  'home': 5,
  'time': 30,
  'age': 27,
  'marital': 1,
  'records': 1,
  'job': 1,
  'expenses': 45,
  'income': 100,
  'assets': 5000,
  'debt': 0,
  'amount': 500,
  'price': 1048},
 {'_id': ObjectId('69bbae32b0c8809709d74394'),
  'status': 1,
  'seniority': 6,
  'home': 2,
  'time': 24,
  'age': 63,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 60,
  'income': 155,
  'assets': 4000,
  'debt': 0,
  'amount': 600,
  'price': 1048},
 {'_id': ObjectId('69bbae32b0c8809709d74395'),
  'status': 1,
  'seniority': 14,
  'home': 2,
  'time': 24,
  'age': 55,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 90,
  'income': 715,
  'assets': 5000,
  'debt': 0,
  'amount': 800,
  'price': 1324},
 {'_id': ObjectId('69bbae32b0c8809709d74396'),
  'status': 1,
  'seniority': 3,
  'home': 1,
  'time': 60,
  'age': 28,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 70,
  'income': 245,
  'assets': 0,
  'debt': 0,
  'amount': 1830,
  'price': 2201},
 {'_id': ObjectId('69bbae32b0c8809709d74397'),
  'status': 1,
  'seniority': 8,
  'home': 1,
  'time': 48,
  'age': 31,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 90,
  'income': 150,
  'assets': 0,
  'debt': 0,
  'amount': 1100,
  'price': 1430},
 {'_id': ObjectId('69bbae32b0c8809709d74398'),
  'status': 2,
  'seniority': 4,
  'home': 5,
  'time': 42,
  'age': 27,
  'marital': 1,
  'records': 1,
  'job': 1,
  'expenses': 35,
  'income': 70,
  'assets': 0,
  'debt': 0,
  'amount': 600,
  'price': 926},
 {'_id': ObjectId('69bbae32b0c8809709d74399'),
  'status': 1,
  'seniority': 22,
  'home': 2,
  'time': 24,
  'age': 40,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 190,
  'assets': 3000,
  'debt': 0,
  'amount': 1000,
  'price': 1500},
 {'_id': ObjectId('69bbae32b0c8809709d7439a'),
  'status': 1,
  'seniority': 2,
  'home': 2,
  'time': 36,
  'age': 35,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 152,
  'assets': 3000,
  'debt': 0,
  'amount': 1000,
  'price': 1542},
 {'_id': ObjectId('69bbae32b0c8809709d7439b'),
  'status': 1,
  'seniority': 15,
  'home': 3,
  'time': 60,
  'age': 43,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 126,
  'assets': 3000,
  'debt': 0,
  'amount': 1350,
  'price': 1360},
 {'_id': ObjectId('69bbae32b0c8809709d7439c'),
  'status': 1,
  'seniority': 10,
  'home': 2,
  'time': 18,
  'age': 34,
  'marital': 2,
  'records': 1,
  'job': 3,
  'expenses': 75,
  'income': 181,
  'assets': 4000,
  'debt': 0,
  'amount': 600,
  'price': 1000},
 {'_id': ObjectId('69bbae32b0c8809709d7439d'),
  'status': 1,
  'seniority': 4,
  'home': 2,
  'time': 60,
  'age': 37,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 60,
  'income': 185,
  'assets': 3000,
  'debt': 0,
  'amount': 1200,
  'price': 1564},
 {'_id': ObjectId('69bbae32b0c8809709d7439e'),
  'status': 1,
  'seniority': 9,
  'home': 2,
  'time': 60,
  'age': 53,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 45,
  'income': 170,
  'assets': 2500,
  'debt': 0,
  'amount': 850,
  'price': 1205},
 {'_id': ObjectId('69bbae32b0c8809709d7439f'),
  'status': 1,
  'seniority': 22,
  'home': 1,
  'time': 60,
  'age': 46,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 93,
  'income': 176,
  'assets': 7500,
  'debt': 0,
  'amount': 2000,
  'price': 2200},
 {'_id': ObjectId('69bbae32b0c8809709d743a0'),
  'status': 1,
  'seniority': 18,
  'home': 5,
  'time': 36,
  'age': 36,
  'marital': 2,
  'records': 1,
  'job': 3,
  'expenses': 60,
  'income': 238,
  'assets': 0,
  'debt': 0,
  'amount': 900,
  'price': 2214},
 {'_id': ObjectId('69bbae32b0c8809709d743a1'),
  'status': 1,
  'seniority': 1,
  'home': 3,
  'time': 60,
  'age': 46,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 60,
  'income': 115,
  'assets': 5500,
  'debt': 800,
  'amount': 1000,
  'price': 1137},
 {'_id': ObjectId('69bbae32b0c8809709d743a2'),
  'status': 1,
  'seniority': 14,
  'home': 2,
  'time': 48,
  'age': 43,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 45,
  'income': 200,
  'assets': 9000,
  'debt': 0,
  'amount': 600,
  'price': 1025},
 {'_id': ObjectId('69bbae32b0c8809709d743a3'),
  'status': 1,
  'seniority': 8,
  'home': 2,
  'time': 36,
  'age': 31,
  'marital': 2,
  'records': 2,
  'job': 3,
  'expenses': 75,
  'income': 411,
  'assets': 9000,
  'debt': 4000,
  'amount': 800,
  'price': 1593},
 {'_id': ObjectId('69bbae32b0c8809709d743a4'),
  'status': 1,
  'seniority': 5,
  'home': 2,
  'time': 24,
  'age': 43,
  'marital': 2,
  'records': 1,
  'job': 1,
  'expenses': 75,
  'income': 93,
  'assets': 3000,
  'debt': 0,
  'amount': 700,
  'price': 1735},
 {'_id': ObjectId('69bbae32b0c8809709d743a5'),
  'status': 1,
  'seniority': 19,

In [106]:
df = pd.DataFrame(list(collection.find()))
df.head()

,_id,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,69bbae32b0c8809709d7435a,1,9,1,60,30,2,1,3,73,129,0,0,800,846
1,69bbae32b0c8809709d7435b,1,17,1,60,58,3,1,1,48,131,0,0,1000,1658
2,69bbae32b0c8809709d7435c,2,10,2,36,46,2,2,3,90,200,3000,0,2000,2985
3,69bbae32b0c8809709d7435d,1,0,1,60,24,1,1,1,63,182,2500,0,900,1325
4,69bbae32b0c8809709d7435e,1,0,1,36,26,1,1,1,46,107,0,0,310,910

In [107]:
df.columns

Index(['_id', 'status', 'seniority', 'home', 'time', 'age', 'marital',
       'records', 'job', 'expenses', 'income', 'assets', 'debt', 'amount',
       'price'],
      dtype='object')

In [108]:
if "_id" in df.columns:
    df = df.drop(columns=["_id"])

In [109]:
df.head()

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,1,9,1,60,30,2,1,3,73,129,0,0,800,846
1,1,17,1,60,58,3,1,1,48,131,0,0,1000,1658
2,2,10,2,36,46,2,2,3,90,200,3000,0,2000,2985
3,1,0,1,60,24,1,1,1,63,182,2500,0,900,1325
4,1,0,1,36,26,1,1,1,46,107,0,0,310,910

In [110]:
df.status.value_counts()

status
1    3200
2    1254
0       1
Name: count, dtype: int64

In [ ]:
status_values = {
1: 'ok',
2: 'default',
0: 'unknown'
}

df.status = df.status.replace(status_values)

'''
"replace" is used for Production-ready code:
Only replaces matching values
Leaves already mapped values unchanged
Safe to run multiple times
'''
df.head()

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,ok,9,1,60,30,2,1,3,73,129,0,0,800,846
1,ok,17,1,60,58,3,1,1,48,131,0,0,1000,1658
2,default,10,2,36,46,2,2,3,90,200,3000,0,2000,2985
3,ok,0,1,60,24,1,1,1,63,182,2500,0,900,1325
4,ok,0,1,36,26,1,1,1,46,107,0,0,310,910

In [113]:
df.status.value_counts()

status
ok         3200
default    1254
unknown       1
Name: count, dtype: int64

In [114]:
df.head()

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,ok,9,1,60,30,2,1,3,73,129,0,0,800,846
1,ok,17,1,60,58,3,1,1,48,131,0,0,1000,1658
2,default,10,2,36,46,2,2,3,90,200,3000,0,2000,2985
3,ok,0,1,60,24,1,1,1,63,182,2500,0,900,1325
4,ok,0,1,36,26,1,1,1,46,107,0,0,310,910

In [115]:
df.home.value_counts()

home
2    2107
1     973
5     783
6     319
3     247
4      20
0       6
Name: count, dtype: int64

In [116]:
home_values = {
1: 'rent',
2: 'owner',
3: 'private',
4: 'ignore',
5: 'parents',
6: 'other',
0: 'unknown'
}

In [117]:
df.home = df.home.replace(home_values)

In [118]:
df.head()

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,ok,9,rent,60,30,2,1,3,73,129,0,0,800,846
1,ok,17,rent,60,58,3,1,1,48,131,0,0,1000,1658
2,default,10,owner,36,46,2,2,3,90,200,3000,0,2000,2985
3,ok,0,rent,60,24,1,1,1,63,182,2500,0,900,1325
4,ok,0,rent,36,26,1,1,1,46,107,0,0,310,910

In [119]:
df.marital.value_counts()

marital
2    3241
1     978
4     130
3      67
5      38
0       1
Name: count, dtype: int64

In [120]:
marital_values = {
1: 'single',
2: 'married',
3: 'widow',
4: 'separated',
5: 'divorced',
0: 'unk'
}

In [121]:
df.marital = df.marital.replace(marital_values)

In [122]:
df.head()

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,ok,9,rent,60,30,married,1,3,73,129,0,0,800,846
1,ok,17,rent,60,58,widow,1,1,48,131,0,0,1000,1658
2,default,10,owner,36,46,married,2,3,90,200,3000,0,2000,2985
3,ok,0,rent,60,24,single,1,1,63,182,2500,0,900,1325
4,ok,0,rent,36,26,single,1,1,46,107,0,0,310,910

In [123]:
df.marital = df.marital.replace({'unk': 'unknown'})

In [124]:
df.head()

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,ok,9,rent,60,30,married,1,3,73,129,0,0,800,846
1,ok,17,rent,60,58,widow,1,1,48,131,0,0,1000,1658
2,default,10,owner,36,46,married,2,3,90,200,3000,0,2000,2985
3,ok,0,rent,60,24,single,1,1,63,182,2500,0,900,1325
4,ok,0,rent,36,26,single,1,1,46,107,0,0,310,910

In [125]:
df.marital.value_counts()

marital
married      3241
single        978
separated     130
widow          67
divorced       38
unknown         1
Name: count, dtype: int64

In [126]:
records_values = {
1: 'no',
2: 'yes',
0: 'unknown'
}

In [127]:
df.records = df.records.replace(records_values)

In [128]:
df.head()

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,ok,9,rent,60,30,married,no,3,73,129,0,0,800,846
1,ok,17,rent,60,58,widow,no,1,48,131,0,0,1000,1658
2,default,10,owner,36,46,married,yes,3,90,200,3000,0,2000,2985
3,ok,0,rent,60,24,single,no,1,63,182,2500,0,900,1325
4,ok,0,rent,36,26,single,no,1,46,107,0,0,310,910

In [129]:
job_values = {
1: 'fixed',
2: 'parttime',
3: 'freelance',
4: 'others',
0: 'unknown'
}

df.job = df.job.replace(job_values)

In [130]:
df.head()

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,ok,9,rent,60,30,married,no,freelance,73,129,0,0,800,846
1,ok,17,rent,60,58,widow,no,fixed,48,131,0,0,1000,1658
2,default,10,owner,36,46,married,yes,freelance,90,200,3000,0,2000,2985
3,ok,0,rent,60,24,single,no,fixed,63,182,2500,0,900,1325
4,ok,0,rent,36,26,single,no,fixed,46,107,0,0,310,910

In [131]:
df.debt.value_counts()

debt
0        3670
2000       59
1500       51
3000       46
1000       39
         ...
130         1
290         1
2432        1
2040        1
23500       1
Name: count, Length: 183, dtype: int64

In [133]:
data = df.to_dict(orient="records")
data

[{'status': 'ok',
  'seniority': 9,
  'home': 'rent',
  'time': 60,
  'age': 30,
  'marital': 'married',
  'records': 'no',
  'job': 'freelance',
  'expenses': 73,
  'income': 129,
  'assets': 0,
  'debt': 0,
  'amount': 800,
  'price': 846},
 {'status': 'ok',
  'seniority': 17,
  'home': 'rent',
  'time': 60,
  'age': 58,
  'marital': 'widow',
  'records': 'no',
  'job': 'fixed',
  'expenses': 48,
  'income': 131,
  'assets': 0,
  'debt': 0,
  'amount': 1000,
  'price': 1658},
 {'status': 'default',
  'seniority': 10,
  'home': 'owner',
  'time': 36,
  'age': 46,
  'marital': 'married',
  'records': 'yes',
  'job': 'freelance',
  'expenses': 90,
  'income': 200,
  'assets': 3000,
  'debt': 0,
  'amount': 2000,
  'price': 2985},
 {'status': 'ok',
  'seniority': 0,
  'home': 'rent',
  'time': 60,
  'age': 24,
  'marital': 'single',
  'records': 'no',
  'job': 'fixed',
  'expenses': 63,
  'income': 182,
  'assets': 2500,
  'debt': 0,
  'amount': 900,
  'price': 1325},
 {'status': 'ok',
  'seniority': 0,
  'home': 'rent',
  'time': 36,
  'age': 26,
  'marital': 'single',
  'records': 'no',
  'job': 'fixed',
  'expenses': 46,
  'income': 107,
  'assets': 0,
  'debt': 0,
  'amount': 310,
  'price': 910},
 {'status': 'ok',
  'seniority': 1,
  'home': 'owner',
  'time': 60,
  'age': 36,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 75,
  'income': 214,
  'assets': 3500,
  'debt': 0,
  'amount': 650,
  'price': 1645},
 {'status': 'ok',
  'seniority': 29,
  'home': 'owner',
  'time': 60,
  'age': 44,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 75,
  'income': 125,
  'assets': 10000,
  'debt': 0,
  'amount': 1600,
  'price': 1800},
 {'status': 'ok',
  'seniority': 9,
  'home': 'parents',
  'time': 12,
  'age': 27,
  'marital': 'single',
  'records': 'no',
  'job': 'fixed',
  'expenses': 35,
  'income': 80,
  'assets': 0,
  'debt': 0,
  'amount': 200,
  'price': 1093},
 {'status': 'ok',
  'seniority': 0,
  'home': 'owner',
  'time': 60,
  'age': 32,
  'marital': 'married',
  'records': 'no',
  'job': 'freelance',
  'expenses': 90,
  'income': 107,
  'assets': 15000,
  'debt': 0,
  'amount': 1200,
  'price': 1957},
 {'status': 'default',
  'seniority': 0,
  'home': 'parents',
  'time': 48,
  'age': 41,
  'marital': 'married',
  'records': 'no',
  'job': 'parttime',
  'expenses': 90,
  'income': 80,
  'assets': 0,
  'debt': 0,
  'amount': 1200,
  'price': 1468},
 {'status': 'ok',
  'seniority': 6,
  'home': 'owner',
  'time': 48,
  'age': 34,
  'marital': 'married',
  'records': 'no',
  'job': 'freelance',
  'expenses': 60,
  'income': 125,
  'assets': 4000,
  'debt': 0,
  'amount': 1150,
  'price': 1577},
 {'status': 'ok',
  'seniority': 7,
  'home': 'owner',
  'time': 36,
  'age': 29,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 60,
  'income': 121,
  'assets': 3000,
  'debt': 0,
  'amount': 650,
  'price': 915},
 {'status': 'ok',
  'seniority': 8,
  'home': 'owner',
  'time': 60,
  'age': 30,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 75,
  'income': 199,
  'assets': 5000,
  'debt': 2500,
  'amount': 1500,
  'price': 1650},
 {'status': 'ok',
  'seniority': 19,
  'home': 'private',
  'time': 36,
  'age': 37,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 75,
  'income': 170,
  'assets': 3500,
  'debt': 260,
  'amount': 600,
  'price': 940},
 {'status': 'default',
  'seniority': 0,
  'home': 'other',
  'time': 18,
  'age': 21,
  'marital': 'single',
  'records': 'yes',
  'job': 'parttime',
  'expenses': 35,
  'income': 50,
  'assets': 0,
  'debt': 0,
  'amount': 400,
  'price': 500},
 {'status': 'ok',
  'seniority': 0,
  'home': 'owner',
  'time': 24,
  'age': 68,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 75,
  'income': 131,
  'assets': 4162,
  'debt': 0,
  'amount': 900,
  'price': 1186},
 {'status': 'ok',
  'seniority': 15,
  'home': 'private',
  'time': 24,
  'age': 52,
  'marital': 'single',
  'records': 'no',
  'job': 'freelance',
  'expenses': 35,
  'income': 330,
  'assets': 16500,
  'debt': 0,
  'amount': 1500,
  'price': 2201},
 {'status': 'ok',
  'seniority': 33,
  'home': 'rent',
  'time': 24,
  'age': 68,
  'marital': 'married',
  'records': 'no',
  'job': 'freelance',
  'expenses': 65,
  'income': 200,
  'assets': 5000,
  'debt': 2000,
  'amount': 600,
  'price': 1350},
 {'status': 'default',
  'seniority': 0,
  'home': 'ignore',
  'time': 48,
  'age': 36,
  'marital': 'married',
  'records': 'no',
  'job': 'parttime',
  'expenses': 45,
  'income': 130,
  'assets': 750,
  'debt': 0,
  'amount': 1100,
  'price': 1511},
 {'status': 'ok',
  'seniority': 1,
  'home': 'parents',
  'time': 60,
  'age': 31,
  'marital': 'single',
  'records': 'no',
  'job': 'fixed',
  'expenses': 35,
  'income': 137,
  'assets': 0,
  'debt': 0,
  'amount': 1250,
  'price': 1253},
 {'status': 'default',
  'seniority': 2,
  'home': 'rent',
  'time': 60,
  'age': 25,
  'marital': 'single',
  'records': 'no',
  'job': 'fixed',
  'expenses': 46,
  'income': 107,
  'assets': 0,
  'debt': 0,
  'amount': 1500,
  'price': 2189},
 {'status': 'ok',
  'seniority': 5,
  'home': 'owner',
  'time': 60,
  'age': 22,
  'marital': 'single',
  'records': 'no',
  'job': 'fixed',
  'expenses': 45,
  'income': 324,
  'assets': 10000,
  'debt': 0,
  'amount': 1100,
  'price': 1159},
 {'status': 'default',
  'seniority': 1,
  'home': 'owner',
  'time': 60,
  'age': 45,
  'marital': 'married',
  'records': 'no',
  'job': 'parttime',
  'expenses': 105,
  'income': 112,
  'assets': 2000,
  'debt': 500,
  'amount': 600,
  'price': 1332},
 {'status': 'ok',
  'seniority': 27,
  'home': 'rent',
  'time': 60,
  'age': 41,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 74,
  'income': 140,
  'assets': 0,
  'debt': 0,
  'amount': 950,
  'price': 1497},
 {'status': 'ok',
  'seniority': 26,
  'home': 'owner',
  'time': 60,
  'age': 51,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 45,
  'income': 143,
  'assets': 3500,
  'debt': 0,
  'amount': 1350,
  'price': 1357},
 {'status': 'ok',
  'seniority': 12,
  'home': 'owner',
  'time': 36,
  'age': 54,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 60,
  'income': 130,
  'assets': 4000,
  'debt': 0,
  'amount': 700,
  'price': 2100},
 {'status': 'ok',
  'seniority': 19,
  'home': 'owner',
  'time': 60,
  'age': 43,
  'marital': 'single',
  'records': 'no',
  'job': 'fixed',
  'expenses': 75,
  'income': 180,
  'assets': 4000,
  'debt': 0,
  'amount': 1000,
  'price': 1070},
 {'status': 'ok',
  'seniority': 15,
  'home': 'owner',
  'time': 36,
  'age': 43,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 75,
  'income': 251,
  'assets': 4000,
  'debt': 0,
  'amount': 1800,
  'price': 2557},
 {'status': 'default',
  'seniority': 3,
  'home': 'owner',
  'time': 24,
  'age': 23,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 75,
  'income': 85,
  'assets': 5000,
  'debt': 0,
  'amount': 600,
  'price': 1600},
 {'status': 'default',
  'seniority': 0,
  'home': 'unknown',
  'time': 48,
  'age': 37,
  'marital': 'single',
  'records': 'no',
  'job': 'unknown',
  'expenses': 35,
  'income': 99999999,
  'assets': 99999999,
  'debt': 99999999,
  'amount': 1500,
  'price': 1850},
 {'status': 'ok',
  'seniority': 4,
  'home': 'owner',
  'time': 48,
  'age': 29,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 45,
  'income': 150,
  'assets': 5000,
  'debt': 3300,
  'amount': 1100,
  'price': 1312},
 {'status': 'default',
  'seniority': 0,
  'home': 'owner',
  'time': 36,
  'age': 23,
  'marital': 'single',
  'records': 'no',
  'job': 'parttime',
  'expenses': 45,
  'income': 122,
  'assets': 2500,
  'debt': 0,
  'amount': 400,
  'price': 400},
 {'status': 'ok',
  'seniority': 14,
  'home': 'private',
  'time': 24,
  'age': 51,
  'marital': 'married',
  'records': 'no',
  'job': 'parttime',
  'expenses': 75,
  'income': 198,
  'assets': 1000,
  'debt': 0,
  'amount': 450,
  'price': 650},
 {'status': 'ok',
  'seniority': 10,
  'home': 'owner',
  'time': 36,
  'age': 39,
  'marital': 'married',
  'records': 'no',
  'job': 'freelance',
  'expenses': 75,
  'income': 150,
  'assets': 3000,
  'debt': 0,
  'amount': 1000,
  'price': 1394},
 {'status': 'ok',
  'seniority': 12,
  'home': 'parents',
  'time': 36,
  'age': 35,
  'marital': 'single',
  'records': 'no',
  'job': 'fixed',
  'expenses': 35,
  'income': 170,
  'assets': 0,
  'debt': 0,
  'amount': 1100,
  'price': 1542},
 {'status': 'ok',
  'seniority': 32,
  'home': 'owner',
  'time': 24,
  'age': 62,
  'marital': 'married',
  'records': 'no',
  'job': 'freelance',
  'expenses': 45,
  'income': 119,
  'assets': 8500,
  'debt': 0,
  'amount': 700,
  'price': 1200},
 {'status': 'ok',
  'seniority': 10,
  'home': 'owner',
  'time': 24,
  'age': 56,
  'marital': 'married',
  'records': 'no',
  'job': 'freelance',
  'expenses': 45,
  'income': 208,
  'assets': 13500,
  'debt': 0,
  'amount': 500,
  'price': 1560},
 {'status': 'ok',
  'seniority': 7,
  'home': 'owner',
  'time': 48,
  'age': 32,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 75,
  'income': 115,
  'assets': 3000,
  'debt': 0,
  'amount': 800,
  'price': 1200},
 {'status': 'default',
  'seniority': 1,
  'home': 'rent',
  'time': 54,
  'age': 36,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 70,
  'income': 99,
  'assets': 0,
  'debt': 0,
  'amount': 950,
  'price': 950},
 {'status': 'ok',
  'seniority': 30,
  'home': 'owner',
  'time': 60,
  'age': 64,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 45,
  'income': 120,
  'assets': 14000,
  'debt': 0,
  'amount': 1125,
  'price': 1300},
 {'status': 'default',
  'seniority': 5,
  'home': 'rent',
  'time': 48,
  'age': 31,
  'marital': 'single',
  'records': 'no',
  'job': 'fixed',
  'expenses': 44,
  'income': 90,
  'assets': 0,
  'debt': 0,
  'amount': 1300,
  'price': 1700},
 {'status': 'ok',
  'seniority': 24,
  'home': 'owner',
  'time': 60,
  'age': 42,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 75,
  'income': 137,
  'assets': 4000,
  'debt': 0,
  'amount': 900,
  'price': 1167},
 {'status': 'ok',
  'seniority': 0,
  'home': 'owner',
  'time': 60,
  'age': 61,
  'marital': 'widow',
  'records': 'no',
  'job': 'others',
  'expenses': 35,
  'income': 230,
  'assets': 50000,
  'debt': 0,
  'amount': 950,
  'price': 1150},
 {'status': 'default',
  'seniority': 0,
  'home': 'owner',
  'time': 60,
  'age': 32,
  'marital': 'married',
  'records': 'yes',
  'job': 'fixed',
  'expenses': 45,
  'income': 142,
  'assets': 7000,
  'debt': 3000,
  'amount': 1250,
  'price': 1566},
 {'status': 'default',
  'seniority': 2,
  'home': 'owner',
  'time': 60,
  'age': 43,
  'marital': 'married',
  'records': 'no',
  'job': 'parttime',
  'expenses': 75,
  'income': 71,
  'assets': 3000,
  'debt': 0,
  'amount': 1500,
  'price': 1552},
 {'status': 'ok',
  'seniority': 1,
  'home': 'parents',
  'time': 60,
  'age': 26,
  'marital': 'single',
  'records': 'no',
  'job': 'parttime',
  'expenses': 35,
  'income': 120,
  'assets': 0,
  'debt': 0,
  'amount': 1150,
  'price': 1300},
 {'status': 'ok',
  'seniority': 1,
  'home': 'owner',
  'time': 60,
  'age': 49,
  'marital': 'widow',
  'records': 'no',
  'job': 'freelance',
  'expenses': 35,
  'income': 233,
  'assets': 15900,
  'debt': 4500,
  'amount': 2100,
  'price': 2104},
 {'status': 'ok',
  'seniority': 15,
  'home': 'owner',
  'time': 36,
  'age': 47,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 75,
  'income': 289,
  'assets': 3500,
  'debt': 0,
  'amount': 1500,
  'price': 2154},
 {'status': 'default',
  'seniority': 2,
  'home': 'rent',
  'time': 36,
  'age': 27,
  'marital': 'separated',
  'records': 'no',
  'job': 'fixed',
  'expenses': 48,
  'income': 128,
  'assets': 0,
  'debt': 0,
  'amount': 450,
  'price': 545},
 {'status': 'ok',
  'seniority': 25,
  'home': 'owner',
  'time': 36,
  'age': 52,
  'marital': 'married',
  'records': 'no',
  'job': 'freelance',
  'expenses': 60,
  'income': 150,
  'assets': 15000,
  'debt': 0,
  'amount': 750,
  'price': 1778},
 {'status': 'ok',
  'seniority': 8,
  'home': 'owner',
  'time': 60,
  'age': 28,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 60,
  'income': 145,
  'assets': 4000,
  'debt': 1000,
  'amount': 1600,
  'price': 1718},
 {'status': 'ok',
  'seniority': 5,
  'home': 'owner',
  'time': 60,
  'age': 31,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 75,
  'income': 90,
  'assets': 4000,
  'debt': 0,
  'amount': 900,
  'price': 1500},
 {'status': 'ok',
  'seniority': 0,
  'home': 'rent',
  'time': 60,
  'age': 32,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 105,
  'income': 301,
  'assets': 0,
  'debt': 0,
  'amount': 1200,
  'price': 1274},
 {'status': 'ok',
  'seniority': 5,
  'home': 'owner',
  'time': 36,
  'age': 51,
  'marital': 'married',
  'records': 'no',
  'job': 'freelance',
  'expenses': 75,
  'income': 200,
  'assets': 2100,
  'debt': 1200,
  'amount': 900,
  'price': 1015},
 {'status': 'ok',
  'seniority': 3,
  'home': 'parents',
  'time': 12,
  'age': 37,
  'marital': 'married',
  'records': 'no',
  'job': 'freelance',
  'expenses': 60,
  'income': 150,
  'assets': 500,
  'debt': 0,
  'amount': 500,
  'price': 1701},
 {'status': 'default',
  'seniority': 1,
  'home': 'rent',
  'time': 48,
  'age': 29,
  'marital': 'married',
  'records': 'yes',
  'job': 'freelance',
  'expenses': 85,
  'income': 100,
  'assets': 0,
  'debt': 0,
  'amount': 1000,
  'price': 1345},
 {'status': 'ok',
  'seniority': 7,
  'home': 'parents',
  'time': 60,
  'age': 26,
  'marital': 'single',
  'records': 'no',
  'job': 'fixed',
  'expenses': 35,
  'income': 100,
  'assets': 0,
  'debt': 0,
  'amount': 1000,
  'price': 1238},
 {'status': 'ok',
  'seniority': 4,
  'home': 'parents',
  'time': 30,
  'age': 27,
  'marital': 'single',
  'records': 'no',
  'job': 'fixed',
  'expenses': 45,
  'income': 100,
  'assets': 5000,
  'debt': 0,
  'amount': 500,
  'price': 1048},
 {'status': 'ok',
  'seniority': 6,
  'home': 'owner',
  'time': 24,
  'age': 63,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 60,
  'income': 155,
  'assets': 4000,
  'debt': 0,
  'amount': 600,
  'price': 1048},
 {'status': 'ok',
  'seniority': 14,
  'home': 'owner',
  'time': 24,
  'age': 55,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 90,
  'income': 715,
  'assets': 5000,
  'debt': 0,
  'amount': 800,
  'price': 1324},
 {'status': 'ok',
  'seniority': 3,
  'home': 'rent',
  'time': 60,
  'age': 28,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 70,
  'income': 245,
  'assets': 0,
  'debt': 0,
  'amount': 1830,
  'price': 2201},
 {'status': 'ok',
  'seniority': 8,
  'home': 'rent',
  'time': 48,
  'age': 31,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 90,
  'income': 150,
  'assets': 0,
  'debt': 0,
  'amount': 1100,
  'price': 1430},
 {'status': 'default',
  'seniority': 4,
  'home': 'parents',
  'time': 42,
  'age': 27,
  'marital': 'single',
  'records': 'no',
  'job': 'fixed',
  'expenses': 35,
  'income': 70,
  'assets': 0,
  'debt': 0,
  'amount': 600,
  'price': 926},
 {'status': 'ok',
  'seniority': 22,
  'home': 'owner',
  'time': 24,
  'age': 40,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 75,
  'income': 190,
  'assets': 3000,
  'debt': 0,
  'amount': 1000,
  'price': 1500},
 {'status': 'ok',
  'seniority': 2,
  'home': 'owner',
  'time': 36,
  'age': 35,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 75,
  'income': 152,
  'assets': 3000,
  'debt': 0,
  'amount': 1000,
  'price': 1542},
 {'status': 'ok',
  'seniority': 15,
  'home': 'private',
  'time': 60,
  'age': 43,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 75,
  'income': 126,
  'assets': 3000,
  'debt': 0,
  'amount': 1350,
  'price': 1360},
 {'status': 'ok',
  'seniority': 10,
  'home': 'owner',
  'time': 18,
  'age': 34,
  'marital': 'married',
  'records': 'no',
  'job': 'freelance',
  'expenses': 75,
  'income': 181,
  'assets': 4000,
  'debt': 0,
  'amount': 600,
  'price': 1000},
 {'status': 'ok',
  'seniority': 4,
  'home': 'owner',
  'time': 60,
  'age': 37,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 60,
  'income': 185,
  'assets': 3000,
  'debt': 0,
  'amount': 1200,
  'price': 1564},
 {'status': 'ok',
  'seniority': 9,
  'home': 'owner',
  'time': 60,
  'age': 53,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 45,
  'income': 170,
  'assets': 2500,
  'debt': 0,
  'amount': 850,
  'price': 1205},
 {'status': 'ok',
  'seniority': 22,
  'home': 'rent',
  'time': 60,
  'age': 46,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 93,
  'income': 176,
  'assets': 7500,
  'debt': 0,
  'amount': 2000,
  'price': 2200},
 {'status': 'ok',
  'seniority': 18,
  'home': 'parents',
  'time': 36,
  'age': 36,
  'marital': 'married',
  'records': 'no',
  'job': 'freelance',
  'expenses': 60,
  'income': 238,
  'assets': 0,
  'debt': 0,
  'amount': 900,
  'price': 2214},
 {'status': 'ok',
  'seniority': 1,
  'home': 'private',
  'time': 60,
  'age': 46,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 60,
  'income': 115,
  'assets': 5500,
  'debt': 800,
  'amount': 1000,
  'price': 1137},
 {'status': 'ok',
  'seniority': 14,
  'home': 'owner',
  'time': 48,
  'age': 43,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 45,
  'income': 200,
  'assets': 9000,
  'debt': 0,
  'amount': 600,
  'price': 1025},
 {'status': 'ok',
  'seniority': 8,
  'home': 'owner',
  'time': 36,
  'age': 31,
  'marital': 'married',
  'records': 'yes',
  'job': 'freelance',
  'expenses': 75,
  'income': 411,
  'assets': 9000,
  'debt': 4000,
  'amount': 800,
  'price': 1593},
 {'status': 'ok',
  'seniority': 5,
  'home': 'owner',
  'time': 24,
  'age': 43,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 75,
  'income': 93,
  'assets': 3000,
  'debt': 0,
  'amount': 700,
  'price': 1735},
 {'status': 'ok',
  'seniority': 19,
  'home': 'rent',
  'time': 60,
  'age': 38,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 86,
  'income': 108,
  'assets': 0,
  'debt': 0,
  'amount': 1000,
  'price': 1132},
 {'status': 'ok',
  'seniority': 14,
  'home': 'owner',
  'time': 12,
  'age': 37,
  'marital': 'married',
  'records': 'no',
  'job': 'freelance',
  'expenses': 90,
  'income': 500,
  'assets': 4000,
  'debt': 0,
  'amount': 500,
  'price': 1338},
 {'status': 'ok',
  'seniority': 0,
  'home': 'other',
  'time': 36,
  'age': 46,
  'marital': 'married',
  'records': 'yes',
  'job': 'others',
  'expenses': 45,
  'income': 45,
  'assets': 0,
  'debt': 0,
  'amount': 900,
  'price': 1100},
 {'status': 'ok',
  'seniority': 9,
  'home': 'rent',
  'time': 36,
  'age': 55,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 70,
  'income': 250,
  'assets': 30000,
  'debt': 0,
  'amount': 1750,
  'price': 2276},
 {'status': 'ok',
  'seniority': 29,
  'home': 'owner',
  'time': 48,
  'age': 56,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 45,
  'income': 100,
  'assets': 3000,
  'debt': 0,
  'amount': 900,
  'price': 1360},
 {'status': 'ok',
  'seniority': 10,
  'home': 'owner',
  'time': 36,
  'age': 55,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 60,
  'income': 70,
  'assets': 4000,
  'debt': 0,
  'amount': 1000,
  'price': 1436},
 {'status': 'ok',

In [132]:
# Variables required for storing data on MongoDB
DB_NAME = "Credit_Scoring_Database"
COLLECTION_NAME = "credit_scoring_data_modified"
CONNECTION_URL = "mongodb+srv://learnermp_db_user:853gv5OEy7RlJ5iV@cluster0.0ariqsg.mongodb.net/?appName=Cluster0"

In [134]:
# Posting data at MongoDb

client = pymongo.MongoClient(CONNECTION_URL)
data_base = client[DB_NAME]
collection = data_base[COLLECTION_NAME]

rec = collection.insert_many(data)